### ISSUE TITLE
发现了Bug和提一些建议！

### ISSUE THREAD

**Issue by MrMiss88** [WEIFENG2333/VideoCaptioner#1]
1.我拖了一个38分钟的视频转录，只转录到了16分钟，断句的时候是看到有38分钟，最后断句优化出来只有16分钟多。

2.目前转录和字幕合成到视频里好像是全流程的，能否增加选项让用户决定要不要字幕合成到视频里面，只转录字幕和优化，而且我拖入的视频只有几百M，转录合成最终的视频出来有1G多，所以压制压缩转码有点问题，视频变大了。

3.字幕优化那里，能否增加自定义，小于多少字独立一行的字幕，要合并一起，因为我看到有些字幕优化后，结果三四个字左右还是一行字的，但是根据易读性是要合并到下一句的才对。或许可以，用户自行排查，对着两行字幕可以右键选择合并一句，或许增加快捷键命令也行。

4.字幕优化了之后，能否增加搜索和批量替换某个字的功能，这个蛮重要的。比如，字幕里经常会用到它，转录很多是他，我需要搜索【他】全部替换成【它】。

5.安装解压包里的主程序图标，快捷方式创建到桌面，有点模糊。

**Comment by WEIFENG2333** [comment]
1. 测试的时候并没遇到过这个情况，方便分享视频来给我测试吗? 或许你配置自己的api接口使用强一点的模型可以解决问题。本软件的公益接口处理效果只是比较一般。
2. 你可以在设置里面开启软字幕功能，这样就不会对视频进行压制。另外，你也可以在页面里面单步处理。 为了兼顾速度本软件压制过程使用ffmpe极快选项，导致压缩率不高，有时候补原有视频大属于正常。
3. 模型是根据语义进行分割的，可能那三四个就就是完整的一句话? 或者尝试使用强一点的llm模型。  关于字幕编辑页面，后面会优化相关的处理的。
4. 使用文本编辑器打开字幕文件，搜索替换即可。
5. 后面会替换为高清图片。

感谢你的反馈。

**Comment by MrMiss88** [comment]
针对第1个问题，38分钟只转录出来16分钟的字幕，我下载的B站50多分钟的视频又试了，这样又没有遇到这个问题，不知道是不是视频编码什么等问题导致的，我测试的那个视频是内部的讲话就不好传给你了。
刚刚又找到了个Bug，只用语音转录那个模块功能，转录出来的字幕会带有逗号【，】，其实作为字幕逗号是可以去掉的，但是全流程转录到合成视频就没有发现逗号这个问题，

**Comment by WEIFENG2333** [comment]
> 针对第1个问题，38分钟只转录出来16分钟的字幕，我下载了B站的一个50多分钟的视频又试了下，这样又没有遇到这个问题，不知道是不是视频编码什么等问题导致的，我测试的那个视频是内部的讲话就不好传给你了。 刚刚又找到了个Bug，只用语音转录那个模块功能，转录出来的字幕会带有逗号【，】，其实作为字幕逗号是可以去掉的，但是全流程转录到合成视频就没有发现逗号这个问题，

这个很好解决，在提示词里面声明不需要标点就可以，后面会逐渐优化。

**Comment by WEIFENG2333** [comment]
问题已经修复，下个版本将更新。
