### ISSUE TITLE
大佬 llm使用api会自动翻译

### ISSUE THREAD

**Issue by GillianJiao** [WEIFENG2333/VideoCaptioner#10]
### 💡 预期的功能 | Expected Feature

这种可以转录成视频的原语言字幕吗，然后再使用字幕翻译与优惠的选项吗，现在使用api转录直接给我翻译了

**Comment by WEIFENG2333** [comment]
关闭“字幕翻译”选项即可

**Comment by GillianJiao** [comment]
我关闭了还是自动翻译了，使用的是本地音频，api使用时j接口 4o

**Comment by WEIFENG2333** [comment]
没有理由啊，我这里一点问题没有。你把字幕优化也关了还是这样吗，使用别的音频也是这样?

**Comment by GillianJiao** [comment]
是的，使用多个音频都是这样而且翻译成出来的内容特别差，尴尬，使用[faster-whisper-GUI](https://github.com/CheshireCC/faster-whisper-GUI)对比区别挺大的，大佬可以看看

**Comment by WEIFENG2333** [comment]
> 是的，使用多个音频都是这样而且翻译成出来的内容特别差，尴尬，使用[faster-whisper-GUI](https://github.com/CheshireCC/faster-whisper-GUI)对比区别挺大的，大佬可以看看

可以提供音频文件吗？
