### ISSUE TITLE
macos15可运行，但后台有很多报错，影响未知

### ISSUE THREAD

**Issue by leonisflying** [WEIFENG2333/VideoCaptioner#101]
期待macos版本的执行程序版本。。。

### 问题描述 | Problem Description

ConnectionResetError: [Errno 54] Connection reset by peer

During handling of the above exception, another exception occurred:

urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))

**Comment by leonisflying** [comment]
期待macos版本的执行程序版本

**Comment by WEIFENG2333** [comment]
这个应该是网络连接的问题，检测版本是否要更新的，也许网络错误原因。

**Comment by WEIFENG2333** [comment]
mac相关的适配欢迎提交pr。

**Comment by philpw99** [comment]
安装包出来了，不过还是需要预先安装 Homebrew, aria2, ffmpeg 和 whisper.cpp

https://github.com/philpw99/VideoCaptioner/releases/tag/v1.2.0_3.5.2_M1_Mac
