### ISSUE TITLE
能加一个限制字幕长度功能

### ISSUE THREAD

**Issue by zdd123456M** [WEIFENG2333/VideoCaptioner#102]
### 💡 预期的功能 | Expected Feature

希望作者大大能加一个限制字幕长度功能

**Comment by zdd123456M** [comment]
作者加油把卡卡字幕助手软件做的更好



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月2日(周一) 下午4:49
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [WEIFENG2333/VideoCaptioner] 能加一个限制字幕长度功能 (Issue #102)




 
已经实现，下个版本会有。
 
PixPin_2024-12-02_16-47-21.png (view on web)

**Comment by zdd123456M** [comment]
还有这个软件老是崩溃作者大大您看看怎么回事



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月2日(周一) 下午4:49
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [WEIFENG2333/VideoCaptioner] 能加一个限制字幕长度功能 (Issue #102)




 
已经实现，下个版本会有。
 
PixPin_2024-12-02_16-47-21.png (view on web)

**Comment by zdd123456M** [comment]
作者大大还有可以设置字幕数量功能



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月2日(周一) 下午4:49
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [WEIFENG2333/VideoCaptioner] 能加一个限制字幕长度功能 (Issue #102)




 
已经实现，下个版本会有。
 
PixPin_2024-12-02_16-47-21.png (view on web)

**Comment by WEIFENG2333** [comment]
> 还有这个软件老是崩溃作者大大您看看怎么回事

这个我重来没遇过。

怎么操作可以复现这个?

**Comment by zdd123456M** [comment]
用着用着就就崩溃了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月3日(周二) 上午8:46
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [WEIFENG2333/VideoCaptioner] 能加一个限制字幕长度功能 (Issue #102)




  
还有这个软件老是崩溃作者大大您看看怎么回事
  
这个我重来没遇过。
 
怎么操作可以复现这个?

**Comment by zdd123456M** [comment]
加油作者把卡卡字幕软件做的更好




---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月2日(周一) 下午4:49
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [WEIFENG2333/VideoCaptioner] 能加一个限制字幕长度功能 (Issue #102)




 
已经实现，下个版本会有。
 
PixPin_2024-12-02_16-47-21.png (view on web)

**Comment by zdd123456M** [comment]
还有加个字幕可以设置数字比如 18或者是 20



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月3日(周二) 上午8:46
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [WEIFENG2333/VideoCaptioner] 能加一个限制字幕长度功能 (Issue #102)




  
还有这个软件老是崩溃作者大大您看看怎么回事
  
这个我重来没遇过。
 
怎么操作可以复现这个?
