### ISSUE TITLE
音频转换失败，输出的wav只有742字节

### ISSUE THREAD

**Issue by Hazukiaoi** [WEIFENG2333/VideoCaptioner#104]
### 问题描述 | Problem Description

拖入本地视频之后尝试语音识别，然后输入Whisper后失败。最后发现视频转换后的wav只有742字节。并且测试多个视频都一样。
![image](https://github.com/user-attachments/assets/484f48a1-d377-48cd-bdb0-24e363fc8c35)

**Comment by WEIFENG2333** [comment]
新版本将修复
