### ISSUE TITLE
今天嘗試了一下 跳掉了兩次

### ISSUE THREAD

**Issue by 123hi123** [WEIFENG2333/VideoCaptioner#105]
### 问题描述 | Problem Description

一次是我在選擇本地模型的時候
按下確定後跳掉
另一次是我忘記了

**Comment by 123hi123** [comment]
剛剛點選批處理文件得時候也跳掉了

**Comment by 123hi123** [comment]
[app.log](https://github.com/user-attachments/files/17995754/app.log)

**Comment by WEIFENG2333** [comment]
下版本修复闪退问题。
