### ISSUE TITLE
多音轨视频可以提供音轨选择吗？

### ISSUE THREAD

**Issue by loengwaifung** [WEIFENG2333/VideoCaptioner#107]
### 💡 预期的功能 | Expected Feature

多音轨视频可以提供音轨选择吗？音频格式可以支持多些吗？电影会停留「正在上传」不动

**Comment by WEIFENG2333** [comment]
多音轨视频暂时只能选择第一条音轨。
音频格式已经是使用ffmpeg支持的格式，市面上所有格式都基本包含了。
在线接口资源有限，不支持过于长的音频，请使用本地Whisper。

**Comment by WEIFENG2333** [comment]
![Image](https://github.com/user-attachments/assets/92d23b50-5026-4e1d-836a-83a39496485c)

1.4 版本支持多音轨选择功能
