### ISSUE TITLE
能增加一个人声活动检查功能

### ISSUE THREAD

**Issue by zdd123456M** [WEIFENG2333/VideoCaptioner#108]
### 💡 预期的功能 | Expected Feature

能增加一个人声活动检查功能
![Screenshot_2024-12-04-14-25-53-396_tv danmaku bili](https://github.com/user-attachments/assets/4e5cedd7-221f-4202-a0cd-1052e6c29c8d)
![Screenshot_2024-12-04-14-26-49-706_tv danmaku bili](https://github.com/user-attachments/assets/1c3c50a5-3185-4f80-ba0a-d47f63a5e669)
![Screenshot_2024-12-04-14-27-45-213_tv danmaku bili](https://github.com/user-attachments/assets/55a8f192-555e-4c41-8d64-a54a273442e8)
![Screenshot_2024-12-04-14-28-06-021_tv danmaku bili](https://github.com/user-attachments/assets/39a50bb5-e267-40dc-960c-6f5e3a5571bf)
![Screenshot_2024-12-04-14-28-24-780_tv danmaku bili](https://github.com/user-attachments/assets/c59cf880-e5a9-42af-aead-02177b988465)
![Screenshot_2024-12-04-14-28-40-561_tv danmaku bili](https://github.com/user-attachments/assets/5c7342d2-b511-4ee1-9587-854a23f5c5d7)
![Screenshot_2024-12-04-14-28-57-058_tv danmaku bili](https://github.com/user-attachments/assets/edc89e8e-3b91-4a79-b703-e5150b430eb9)

**Comment by WEIFENG2333** [comment]
下版本已经支持vad

**Comment by zdd123456M** [comment]
辛苦了作者大大



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月4日(周三) 下午3:27
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [WEIFENG2333/VideoCaptioner] 能增加一个人声活动检查功能 (Issue #108)




 
下版本已经支持vad
