### ISSUE TITLE
某些.srt字幕文件会导致闪退

### ISSUE THREAD

**Issue by Kloorfans** [WEIFENG2333/VideoCaptioner#11]
### 问题描述 | Problem Description

我是从https://www.subtitlecat.com/ 下载字幕,随机下载几个srt字幕文件,有些srt导入后会闪退.大概率,10个有7个是会闪退的,提供一个我会闪退的字幕文件给你试试
[BR.zip](https://github.com/user-attachments/files/17778743/BR.zip)

**Comment by ganen1933** [comment]
字符数多的SRT文件确实闪退，测试发现添加超过30KB的SRT字幕文件就闪退，30KB以下的字幕不闪退，不知道是不是这个原因

**Comment by Kloorfans** [comment]
文件大小是闪退的原因之一吧,我觉得并不是主要原因,因为我这里试过一个50kb的文件,600多行,是可以正常翻译的.
[S01E01-pt-BR.zip](https://github.com/user-attachments/files/17783857/S01E01-pt-BR.zip)

我还发现,将会闪退的srt文件删减一些(具体要删多少我没试过,我直接删剩下1行),是可以正常导入,不会闪退的.

**Comment by WEIFENG2333** [comment]
经过测试是处理的str文件有点问题，比如它是含有多个换行的，比如：

```
156
00:10:23,140 --> 00:10:27,100
[Guilherme] É nóis!
[Giovanna] Promete trazer o que
tiver pra animar, pra dar um levante?
```

默认认为第一行是原字幕，第二行是翻译字幕。超过3行的就出现问题。

程序导出的逻辑就是这样的（第一行是原字幕，第二行是翻译字幕）。如果处理软件导出的字幕就不会有问题。处理其他地方的字幕就可能不匹配。

很难去做适配，当把导入的内容全视作原字幕又可能忽略了翻译。

现在已经修复，只是尽可能做适配，保证不闪退。
