### ISSUE TITLE
希望可以开发纯字幕导出的功能，合成视频占用时间太长了

### ISSUE THREAD

**Issue by Saddie135** [WEIFENG2333/VideoCaptioner#110]
### 💡 预期的功能 | Expected Feature

我在追英语播客，对画面字幕没有要求，平时主要用外挂字幕或者直接对照文本来看。这个软件功能很棒，翻译到位的同时又断句正确，帮我解决了普通机翻字幕没法翻译出专业含义的困扰。可惜的是，软件在字幕和视频合成这一步会占用较多时间和内存，我每次都要手动删除合成视频保留字幕，如果可以还是希望能有单纯翻译导出字幕的功能，谢谢大大！

**Comment by WEIFENG2333** [comment]
![PixPin_2024-12-05_16-35-21](https://github.com/user-attachments/assets/6a8b8af5-fc38-4f0b-bf7f-55555b99b11a)

下版本支持

**Comment by WEIFENG2333** [comment]
> 如果可以还是希望能有单纯翻译导出字幕的功能

你直接在“字幕优化与翻译”页面处理就是单纯翻译导出字幕的功能

**Comment by Saddie135** [comment]
> > 如果可以还是希望能有单纯翻译导出字幕的功能
> 
> 你直接在“字幕优化与翻译”页面处理就是单纯翻译导出字幕的功能

我下的版本没有

> ![PixPin_2024-12-05_16-35-21](https://private-user-images.githubusercontent.com/61730227/392722248-6a8b8af5-fc38-4f0b-bf7f-55555b99b11a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzOTYyNTcsIm5iZiI6MTczMzM5NTk1NywicGF0aCI6Ii82MTczMDIyNy8zOTI3MjIyNDgtNmE4YjhhZjUtZmMzOC00ZjBiLWJmN2YtNTU1NTViOTliMTFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA1VDEwNTIzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxMWJhMTcwMmQwZWNjN2UyODk5Mzk5MTliZjRlMDI3OTY1ZDZlNjY3YTA0YzQ0NWQ1MGQ1MTkxYzE1YzU4ZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.W88RpHPtXXM2vJgn7K7F1JgxNLwnYDCjBsj39DOsJQQ)
> 
> 下版本支持

我下的版本没有看到这个按钮，我重新下一下看看，谢谢回复！
