### ISSUE TITLE
作者希望加一个人声活动检测功能

### ISSUE THREAD

**Issue by zdd123456M** [WEIFENG2333/VideoCaptioner#111]
### 💡 预期的功能 | Expected Feature

作者希望加一个功能 Silero VAD
![PixPin_2024-12-05_15-11-08](https://github.com/user-attachments/assets/689d199e-5894-4ba9-a44a-77b2eff5a1c2)
![PixPin_2024-12-05_15-15-08](https://github.com/user-attachments/assets/b83c916a-a982-4f89-808c-b615f3cf34ed)

**Comment by WEIFENG2333** [comment]
#108

![image](https://github.com/user-attachments/assets/ddd6a238-2d8c-4b6c-b588-2827aec48aad)

**Comment by zdd123456M** [comment]
感谢作者大大了
