### ISSUE TITLE
实际使用这类软件很多都是像我这样的小白，希望能出多给一些引导说明

### ISSUE THREAD

**Issue by laoyao1983** [WEIFENG2333/VideoCaptioner#112]
### 💡 预期的功能 | Expected Feature

比如如何用LLM API 配置。谢谢！

**Comment by WEIFENG2333** [comment]
有相关的说明，[https://github.com/WEIFENG2333/VideoCaptioner/blob/master/docs/llm_config.md](https://github.com/WEIFENG2333/VideoCaptioner/blob/master/docs/llm_config.md)

由于个人精力有限，只能点到为止，希望可以有人可以共建文档。
