### ISSUE TITLE
b站能不能匹配稍后观看列表的视频下载

### ISSUE THREAD

**Issue by Noah1995** [WEIFENG2333/VideoCaptioner#113]
### 问题描述 | Problem Description

https://www.bilibili.com/list/watchlater?bvid=BV*

**Comment by WEIFENG2333** [comment]
那只能使用b站视频链接

**Comment by Noah1995** [comment]
> 那只能使用b站视频链接
不能转化为吗？
BV号不是一样的额
https://www.bilibili.com/video/BV

**Comment by WEIFENG2333** [comment]
由于使用的是强大的`yt-dlp`库，原来的不支持这个也不支持，不打算二开。
