### ISSUE TITLE
如何使用智谱的API BASE

### ISSUE THREAD

**Issue by laoyao1983** [WEIFENG2333/VideoCaptioner#114]
### 🤔 问题描述 Problem Description

我想使用智谱的glm-4-flash，但是每次在API BASE上发生错误。我是小白，我查到glm-4-flash的URL为：https://open.bigmodel.cn/api/paas/v4/chat/completions          非常想学习使用您的这款软件，方便的话请告知

**Comment by WEIFENG2333** [comment]
填入：`https://open.bigmodel.cn/api/paas/v4`

**Comment by tjsky** [comment]
API Base：`https://open.bigmodel.cn/api/paas/v4`
模型：`glm-4-flash`
