### ISSUE TITLE
添加其他LLM模型api，比如Gemini api 

### ISSUE THREAD

**Issue by zhaoxiaopeng3** [WEIFENG2333/VideoCaptioner#116]
### 💡 预期的功能 | Expected Feature

添加其他LLM模型api，比如Gemini api， 免费额度多，或者本地模型api。或者谷歌，百度的免费api

**Comment by WEIFENG2333** [comment]
精力有限，暂时不打算支持。

可以使用`oneapi`等进行转换为兼容OpenAI格式进行使用。
