### ISSUE TITLE
建议：建立社区交流群

### ISSUE THREAD

**Issue by chmod777john** [WEIFENG2333/VideoCaptioner#12]
相当不错的项目，我认为很有机会变成一个好的产品，可以考虑建立一个社区群聊。issue 和 PR 是很好，但相对来说比较静态；我建议弄一个微信交流群，社区成员实时的沟通能起到头脑风暴的效果，有些好的特性可以在讨论中诞生。一个好的例子是 https://github.com/Zeyi-Lin/HivisionIDPhotos/issues/28 ，社区群里面的日常讨论催生了很多新的想法

![image](https://github.com/user-attachments/assets/a1c331d8-a306-4b6c-9bd4-e3c815edaaaf)

**Comment by WEIFENG2333** [comment]
会考虑的
