### ISSUE TITLE
希望可以在設置中設定使用的最大vram

### ISSUE THREAD

**Issue by 123hi123** [WEIFENG2333/VideoCaptioner#120]
### 💡 预期的功能 | Expected Feature

之前在使用的時候會無情跑滿gpu導致其他要用顯存做的事情卡住
平常顯存用的不多
但如果可以用設定的方式預留1g左右將會很不錯

**Comment by WEIFENG2333** [comment]
这个功能暂时无法实现。

获取您可以使用通过其他软件来达到限制效果。
