### ISSUE TITLE
请问a卡是不是不适合用

### ISSUE THREAD

**Issue by hieverysucker** [WEIFENG2333/VideoCaptioner#124]
### 🤔 问题描述 Problem Description

你好，我是小白，我想请问a卡是不适合用于这个软件，还是我的配置太低了，我是r5 5600+6750gre10g，使用WhisperCpp和large-v1模型翻译日语的时候，前面显卡能跑满，然后过程中占用就降到0％，任务也卡住了，稍微小点的视频就没有这个问题。还有就是如果换成n卡的话4060够吗？非常感谢。

**Comment by WEIFENG2333** [comment]
WhisperCpp可以使用A卡

换成n卡的话就支持CUDA加速，可以使用faster-whisper这个效果更好的。4060使妥妥够的
