### ISSUE TITLE
安装一次以后第二次想重新安装就无法自定义安装位置

### ISSUE THREAD

**Issue by flyricci** [WEIFENG2333/VideoCaptioner#128]
### 问题描述 | Problem Description

我第一次安装时候有出现选择安装位置的选项，但是我选错了位置，然后我卸载以后重新安装，就只会默认安装到之前的位置，我无法重新选择安装位置，重启电脑也不行

**Comment by flyricci** [comment]
我自己复制粘贴移动文件夹也不行，文件夹里没有启动图标，我如果移动了位置，默认的那个启动图标就会失效

**Comment by WEIFENG2333** [comment]
说明你没有卸载干净。

**Comment by WEIFENG2333** [comment]
> 我自己复制粘贴移动文件夹也不行，文件夹里没有启动图标，我如果移动了位置，默认的那个启动图标就会失效

文件夹是有主程序 `VideoCaptioner.exe` 的，你移动了位置，原本的快捷方式当然会失效。
