### ISSUE TITLE
不能下载whisper模型，显示错误

### ISSUE THREAD

**Issue by majunwuxi** [WEIFENG2333/VideoCaptioner#13]
### 问题描述 | Problem Description

点击下载模型时，显示了一条错误的信息：错误 'gbk' codec can't decode byte 0x9b in position 191: illegal multibyte sequence
![VideoCaptioner_yyf9mxPj0D](https://github.com/user-attachments/assets/7d159b47-6b6d-4610-a61c-1855a56b0372)

**Comment by WEIFENG2333** [comment]
你的程序是解压在哪里的?是中文路径吗?

**Comment by majunwuxi** [comment]
是的，改成了英文路径之后就解决了

**Comment by WEIFENG2333** [comment]
> 是的，改成了英文路径之后就解决了

好的，可能命令行调用 `aria2c.exe` 下载的编码有问题。

在 subprocess.Popen() 调用中添加了 encoding='utf-8' 参数，明确指定使用UTF-8编码来处理输入输出流。

问题现在已经修复，下个版本跟新将推送。

感谢你的反馈~
