### ISSUE TITLE
设置cuda，但是cpu占用高

### ISSUE THREAD

**Issue by azwwz** [WEIFENG2333/VideoCaptioner#133]
### 🤔 问题描述 Problem Description

如图
![Snipaste_2024-12-11_09-55-53](https://github.com/user-attachments/assets/5943171b-d38c-4a70-9ad6-fd0042624942)
![Snipaste_2024-12-11_09-56-14](https://github.com/user-attachments/assets/02d213d8-b929-4b6c-b603-d3d773194f30)
![Snipaste_2024-12-11_09-57-16](https://github.com/user-attachments/assets/bf3e88e1-79b0-44a4-bde5-ad89799fbe6f)
已经尝试重启过程序，也重启过电脑

**Comment by WEIFENG2333** [comment]
你不应该只看cpu占用，应该看你的显卡占用。

cpu和gpu是协同工作的。

**Comment by azwwz** [comment]
哦~，
![image](https://github.com/user-attachments/assets/0863416c-6b3a-46bd-a2a5-865684e484b7)
![image](https://github.com/user-attachments/assets/32b38d33-262b-4bcb-9899-a9f4f76b511f)
任务管理器看到的gpu占用，和电脑管家的不太一样
