### ISSUE TITLE
虚拟环境运行报错

### ISSUE THREAD

**Issue by alpaca121** [WEIFENG2333/VideoCaptioner#14]
### 问题描述 | Problem Description

Mac下采用venv虚拟环境配置，pip依赖安装完成后运行报错
![000158-20241116-15 05 38O7Hq1XNb@2x](https://github.com/user-attachments/assets/db707e45-e089-42d6-a2a1-ca7f48816d5b)

**Comment by WEIFENG2333** [comment]
我犯了一个低级错误，原代码中设置根目录路径时两次选择了父文件夹，导致根目录设置错误：

```python
# 添加项目根目录到 Python 路径
current_dir = os.path.dirname(os.path.abspath(__file__))
project_root = os.path.dirname(current_dir)
sys.path.append(project_root)
```

现在问题已修复。

另外，针对mac我并没有做出适配，没有mac电脑。不知道会不会出现一些其他问题，如果有就可以继续反馈。

**Comment by philpw99** [comment]
Mac 安装包出来了，不过还是需要预先安装 Homebrew, aria2, ffmpeg 和 whisper.cpp

https://github.com/philpw99/VideoCaptioner/releases/tag/v1.2.0_3.5.2_M1_Mac
