### ISSUE TITLE
多大的本地文件合成不会出现问题？

### ISSUE THREAD

**Issue by qinshao99** [WEIFENG2333/VideoCaptioner#140]
### 🤔 问题描述 Problem Description

本地文件，1080p的视频，大小为3.5G，最后合成出现一个1k的视频文件，这个是怎么回事呢

**Comment by WEIFENG2333** [comment]
字幕有成功处理吗？

**Comment by WEIFENG2333** [comment]
可能是ffmpeg合成字幕视频时的问题，重新在“字幕视频合成”页面导入视频和字幕合成一下。
