### ISSUE TITLE
可以增加whisper V3模型 和导出翻译后的字幕可选择下载仅译文字幕或双语字幕吗

### ISSUE THREAD

**Issue by ganen1933** [WEIFENG2333/VideoCaptioner#15]
### 💡 预期的功能 | Expected Feature

感谢大佬的开源项目，翻译字幕的质量有明显提高，whisper V3模型在某些场景和语种转录的准确率比V2要高的，翻译好的字幕可以加个选项导出仅译文或者导出双语字幕 ，能支持批量翻译字幕就更方便了。

**Comment by WEIFENG2333** [comment]
large-v3 模型已增加；
字幕排布（选项有“译文在上”“原文在上”“仅译文”“仅原文”）可在字幕样式设置中更改。作为常用选项，也已在字幕优化页面添加。

上述问题已处理，更新将在下个版本推出。
