### ISSUE TITLE
几个 长（4+小时），短（1小时）视频转录都失败，请问如何解决？

### ISSUE THREAD

**Issue by cen798** [WEIFENG2333/VideoCaptioner#151]
### 🤔 问题描述 Problem Description

![语音字幕转录](https://github.com/user-attachments/assets/bf6a35da-4837-48c6-ab5d-dfb876019152)
在1.1版本时，larger v2 比较短视频能转录完成。1.2版本 选择 fasterwhisper  larger-v3 模型  长（4+小时），短（1小时）视频都不能转录成功。请问，对转录字幕的视频文件时长，大小，格式有限制么？遇到这种情况如何解决？谢谢！

**Comment by qinshao99** [comment]
如果视频是全英文的，建议使用 small ，而且在语音转录的过程中，非常非常的吃内存，我16G的内存 都不够，基本上都是转到95%就过不去了，直接转录失败，尝试过把视频和音频分离，只转音频，只有200多M的音频文件，同样内存占满39个G，折腾了一晚上。就是 用 fasterwhisper  small 模型，另外，短期内建议增加一下 虚拟内存，要稍微好点，大一点的视频 基本上转录都会失败，今天又买了2跟内存。如果你那边解决了有好的办法 说一下哈

**Comment by WEIFENG2333** [comment]
有相关日志吗？

**Comment by qinshao99** [comment]
日志删了，我把软件都删了，重新下的，用资源管理器看的

**Comment by theawesomeharris** [comment]
今天用b接口和你情况一样，换j接口直接卡在正在上传。文件小你一半，视频长度差不多4小时多。

**Comment by WEIFENG2333** [comment]
> 今天用b接口和你情况一样，换j接口直接卡在正在上传。文件小你一半，视频长度差不多4小时多。

这么长的视频就不要使用在线接口了

**Comment by WEIFENG2333** [comment]
> ### 🤔 问题描述 Problem Description
> ![语音字幕转录](https://private-user-images.githubusercontent.com/104133332/395760208-bf6a35da-4837-48c6-ab5d-dfb876019152.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzNTE2NTgsIm5iZiI6MTczNDM1MTM1OCwicGF0aCI6Ii8xMDQxMzMzMzIvMzk1NzYwMjA4LWJmNmEzNWRhLTQ4MzctNDhjNi1hYjVkLWRmYjg3NjAxOTE1Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNlQxMjE1NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NmE3NzA3MzVmMDg0ODIyYjcyOTEwNmE2ZjYyNzFmMThmMWNkN2FjNjQ5NDA5MWNiYjc0MTYzOTA2ZWU0Y2M0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ZuPRS2UWE-lgjMWmNQSqbnxwrRmFAldQpCQCz8fWe8s) 在1.1版本时，larger v2 比较短视频能转录完成。1.2版本 选择 fasterwhisper larger-v3 模型 长（4+小时），短（1小时）视频都不能转录成功。请问，对转录字幕的视频文件时长，大小，格式有限制么？遇到这种情况如何解决？谢谢！

软件的本地接口对视频文件时长没有限制的，如果你下次遇到再把日志发我看看吧~

**Comment by cen798** [comment]
> > ### 🤔 问题描述 Problem Description
> > ![语音字幕转录](https://private-user-images.githubusercontent.com/104133332/395760208-bf6a35da-4837-48c6-ab5d-dfb876019152.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzNTE2NTgsIm5iZiI6MTczNDM1MTM1OCwicGF0aCI6Ii8xMDQxMzMzMzIvMzk1NzYwMjA4LWJmNmEzNWRhLTQ4MzctNDhjNi1hYjVkLWRmYjg3NjAxOTE1Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNlQxMjE1NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NmE3NzA3MzVmMDg0ODIyYjcyOTEwNmE2ZjYyNzFmMThmMWNkN2FjNjQ5NDA5MWNiYjc0MTYzOTA2ZWU0Y2M0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ZuPRS2UWE-lgjMWmNQSqbnxwrRmFAldQpCQCz8fWe8s) 在1.1版本时，larger v2 比较短视频能转录完成。1.2版本 选择 fasterwhisper larger-v3 模型 长（4+小时），短（1小时）视频都不能转录成功。请问，对转录字幕的视频文件时长，大小，格式有限制么？遇到这种情况如何解决？谢谢！
> 
> 软件的本地接口对视频文件时长没有限制的，如果你下次遇到再把日志发我看看吧~

好的。谢谢哈。日志是直接点击 转录失败  按钮就能看到吧

**Comment by cen798** [comment]
> 如果视频是全英文的，建议使用 small ，而且在语音转录的过程中，非常非常的吃内存，我16G的内存 都不够，基本上都是转到95%就过不去了，直接转录失败，尝试过把视频和音频分离，只转音频，只有200多M的音频文件，同样内存占满39个G，折腾了一晚上。就是 用 fasterwhisper small 模型，另外，短期内建议增加一下 虚拟内存，要稍微好点，大一点的视频 基本上转录都会失败，今天又买了2跟内存。如果你那边解决了有好的办法 说一下哈

好的，我先试试哈，有新解决办法发你
