### ISSUE TITLE
希望增加导入srt文件，输出字幕以单个词语出现的功能

### ISSUE THREAD

**Issue by fabulous2023** [WEIFENG2333/VideoCaptioner#152]
### 💡 预期的功能 | Expected Feature

希望增加导入srt文件，输出字幕以单个词语出现的功能，参考视频：https://www.youtube.com/shorts/Ykvwwjtivcc
![image](https://github.com/user-attachments/assets/c7822175-bbda-47f0-a497-49c15cf8aa78)
![image](https://github.com/user-attachments/assets/d32cc386-db53-43b9-9409-931881782108)

**Comment by WEIFENG2333** [comment]
原本字幕的时间信息是一句话的话，那么理论就无法实现。

从一句话的时间戳转为一个个字的精确时间戳必然无法实现
