### ISSUE TITLE
本地转录为什么这么吃内存？

### ISSUE THREAD

**Issue by qinshao99** [WEIFENG2333/VideoCaptioner#153]
### 🤔 问题描述 Problem Description

本地文件转录非常的吃内存，我16G的内存，只转录全部吃满，而且基本上都是到了95%就会转录失败，而且跟本地文件的大小不太相关，2个G的文件会占满内存，200M的也会占满？软件确实比其他的要好用一些，有什么的解决办法，麻烦说一下，我今天又买了2跟内存，一只用虚拟内存，对固态硬盘寿命有影响

**Comment by WEIFENG2333** [comment]
你使用的什么那个Whisper模型？FasterWhisper吗？使用CPU进行转录的吗？

**Comment by qinshao99** [comment]
fasterwhisper ，GPU 转录的

**Comment by WEIFENG2333** [comment]
gpu使用的是显存，调用模型转录耗算力是很正常的事情。

**Comment by WEIFENG2333** [comment]
虚拟内存没有任何作用。
