### ISSUE TITLE
希望添加大模型免费接口

### ISSUE THREAD

**Issue by theawesomeharris** [WEIFENG2333/VideoCaptioner#158]
### 💡 预期的功能 | Expected Feature

目前B和J接口挺好用的，只是限制于两个语言。请问这两个接口时基于哪个模型呀？

有没有机会增加大模型免费接口增加多语言支持呀？本地部署有点吃力带不动。感恩感谢。

**Comment by WEIFENG2333** [comment]
可以使用自己的API,参考 [LLM配置](https://github.com/WEIFENG2333/VideoCaptioner/blob/master/docs/llm_config.md)
