### ISSUE TITLE
字幕视频合成功能添加选项

### ISSUE THREAD

**Issue by theawesomeharris** [WEIFENG2333/VideoCaptioner#159]
### 💡 预期的功能 | Expected Feature

希望字幕视频合成功能可以添加
1. 暂停 、终止键，因为有时候只想提取srt文件，没有硬编码的需求
2. 勾选不自动合成

感恩感谢。

**Comment by WEIFENG2333** [comment]
现在设置页面有“不自动合成”的选项。
