### ISSUE TITLE
配置星火认识平台，选择4.0Ultra模型无法连接，测试连接不通过

### ISSUE THREAD

**Issue by asp3000** [WEIFENG2333/VideoCaptioner#165]
### 问题描述 | Problem Description

配置星火认识平台，选择4.0Ultra模型无法连接，测试连接不通过
APIKEY从对应模型中复制过来的，
Base URL是参考官方文档配置的：https://spark-api-open.xf-yun.com/v1/chat/completions
模型名为：4.0Ultra
测试连接时报错提示：LLM 连接测试错误 Error code: 401 - {'message': "HMAC signature cannot be verified:enforced header "host' not used for signature creation"}

**Comment by WEIFENG2333** [comment]
你应该填写: `https://spark-api-open.xf-yun.com/v1`

**Comment by asp3000** [comment]
> 你应该填写: `https://spark-api-open.xf-yun.com/v1`

试过也不行，不知道是不是因为模型的问题还是什么，换腾讯的就可以，讯飞的不行

**Comment by WEIFENG2333** [comment]
根据文档是支持OpenAIg格式的，https://www.xfyun.cn/doc/spark/HTTP%E8%B0%83%E7%94%A8%E6%96%87%E6%A1%A3.html#_7-%E4%BD%BF%E7%94%A8openai-sdk%E8%AF%B7%E6%B1%82%E7%A4%BA%E4%BE%8B

兼容OpenAI格式的软件都可以的，你再次查看模型是否填写正确？

**Comment by asp3000** [comment]
测试通过可正常使用

**Comment by pepeei** [comment]
请问你最后如何解决的?我遇到了同样的问题
