### ISSUE TITLE
新版本字幕样式无法修改，不管改什么颜色或者改内置的其他样式都只会出来白色字体，怎么修改都没有用

### ISSUE THREAD

**Issue by flyricci** [WEIFENG2333/VideoCaptioner#169]
### 问题描述 | Problem Description

新版本字幕样式无法修改，不管改什么颜色或者改内置的其他样式都只会出来白色字体，怎么修改都没有用

**Comment by flyricci** [comment]
我卸载以后重新安装上个月的版本，字幕就正常能修改了，还好上个月下载的还没删

**Comment by WEIFENG2333** [comment]
是你开了软字幕吧？

**Comment by KeivinQian996** [comment]
我也一样，1.2版本，使用硬字幕导出一样中英文都是白字黑色描边。

**Comment by WEIFENG2333** [comment]
> 我也一样，1.2版本，使用硬字幕导出一样中英文都是白字黑色描边。

问题解决了吗，导出的ass样式字幕文件可以截取前面部分来看看吗？

**Comment by KeivinQian996** [comment]
应该是软硬字幕的问题，后面试了下用硬字幕可以，我再试试，如果有问题我再反馈，谢谢哈
