### ISSUE TITLE
转录视频失败

### ISSUE THREAD

**Issue by SlippyJimmy** [WEIFENG2333/VideoCaptioner#174]
### 问题描述 | Problem Description

不管是用本地的fast-whisper还是云端whisper-api都报错

### 日志信息（可选）| Logs (Optional)

```shell
===========转录任务开始===========
时间：2024-12-20 09:49:06.905225
开始转换音频
转换为音频执行命令: ffmpeg -i F:\AI\nakama\part2\Integrating Nakama Into Godot 4.2 Groups Chats and Web OH MY! Part 2.mp4 -map 0:a -ac 1 -ar 16000 -af aresample=async=1 -y D:\VideoCaptioner\work-dir\Integrating Nakama Into Godot 4.2 Groups Chats and Web OH MY! Part 2\【Audio】Integrating Nakama Into Godot 4.2 Groups Chats and Web OH MY! Part 2.wav
开始语音转录
Faster Whisper 执行命令: faster-whisper-xxl.exe -m large-v2 --print_progress --model_dir D:\VideoCaptioner\AppData\models C:\Users\Joewen\AppData\Local\Temp\bk_asr\tmp4nq9_62z\audio.wav -l en -d cuda --output_format srt -o source --vad_filter true --vad_threshold 0.40 --vad_method silero_v3 --one_word 1 --prompt Nakama godot Game Digital Ocean
usage: faster-whisper-xxl.exe [-h] [--model MODEL] [--model_dir MODEL_DIR]
[--device DEVICE] [--output_dir OUTPUT_DIR]
[--output_format [{json,lrc,txt,text,vtt,srt,tsv,all} ...]]
[--verbose VERBOSE]
[--task {transcribe,translate}]
[--language {af,am,ar,as,az,ba,be,bg,bn,bo,br,bs,ca,cs,cy,da,de,el,en,es,et,eu,fa,fi,fo,fr,gl,gu,ha,haw,he,hi,hr,ht,hu,hy,id,is,it,ja,jw,ka,kk,km,kn,ko,la,lb,ln,lo,lt,lv,mg,mi,mk,ml,mn,mr,ms,mt,my,ne,nl,nn,no,oc,pa,pl,ps,pt,ro,ru,sa,sd,si,sk,sl,sn,so,sq,sr,su,sv,sw,ta,te,tg,th,tk,tl,tr,tt,uk,ur,uz,vi,yi,yo,yue,zh,Afrikaans,Albanian,Amharic,Arabic,Armenian,Assamese,Azerbaijani,Bashkir,Basque,Belarusian,Bengali,Bosnian,Breton,Bulgarian,Burmese,Cantonese,Castilian,Catalan,Chinese,Croatian,Czech,Danish,Dutch,English,Estonian,Faroese,Finnish,Flemish,French,Galician,Georgian,German,Greek,Gujarati,Haitian,Haitian Creole,Hausa,Hawaiian,Hebrew,Hindi,Hungarian,Icelandic,Indonesian,Italian,Japanese,Javanese,Kannada,Kazakh,Khmer,Korean,Lao,Latin,Latvian,Letzeburgesch,Lingala,Lithuanian,Luxembourgish,Macedonian,Malagasy,Malay,Malayalam,Maltese,Mandarin,Maori,Marathi,Moldavian,Moldovan,Mongolian,Myanmar,Nepali,Norwegian,Nynorsk,Occitan,Panjabi,Pashto,Persian,Polish,Portuguese,Punjabi,Pushto,Romanian,Russian,Sanskrit,Serbian,Shona,Sindhi,Sinhala,Sinhalese,Slovak,Slovenian,Somali,Spanish,Sundanese,Swahili,Swedish,Tagalog,Tajik,Tamil,Tatar,Telugu,Thai,Tibetan,Turkish,Turkmen,Ukrainian,Urdu,Uzbek,Valencian,Vietnamese,Welsh,Yiddish,Yoruba}]
[--language_detection_threshold LANGUAGE_DETECTION_THRESHOLD]
[--language_detection_segments LANGUAGE_DETECTION_SEGMENTS]
[--temperature TEMPERATURE] [--best_of BEST_OF]
[--beam_size BEAM_SIZE] [--patience PATIENCE]
[--length_penalty LENGTH_PENALTY]
[--repetition_penalty REPETITION_PENALTY]
[--no_repeat_ngram_size NO_REPEAT_NGRAM_SIZE]
[--suppress_blank SUPPRESS_BLANK]
[--suppress_tokens SUPPRESS_TOKENS]
[--initial_prompt INITIAL_PROMPT]
[--prefix PREFIX]
[--condition_on_previous_text CONDITION_ON_PREVIOUS_TEXT]
[--prompt_reset_on_temperature PROMPT_RESET_ON_TEMPERATURE]
[--without_timestamps WITHOUT_TIMESTAMPS]
[--max_initial_timestamp MAX_INITIAL_TIMESTAMP]
[--temperature_increment_on_fallback TEMPERATURE_INCREMENT_ON_FALLBACK]
[--compression_ratio_threshold COMPRESSION_RATIO_THRESHOLD]
[--logprob_threshold LOGPROB_THRESHOLD]
[--no_speech_threshold NO_SPEECH_THRESHOLD]
[--v3_offsets_off]
[--hallucination_silence_threshold HALLUCINATION_SILENCE_THRESHOLD]
[--hallucination_silence_th_temp {0.0,0.2,0.5,0.8,1.0}]
[--clip_timestamps CLIP_TIMESTAMPS]
[--no_speech_strict_lvl {0,1,2}]
[--word_timestamps WORD_TIMESTAMPS]
[--highlight_words HIGHLIGHT_WORDS]
[--prepend_punctuations PREPEND_PUNCTUATIONS]
[--append_punctuations APPEND_PUNCTUATIONS]
[--threads THREADS] [--version]
[--vad_filter VAD_FILTER]
[--vad_threshold VAD_THRESHOLD]
[--vad_min_speech_duration_ms VAD_MIN_SPEECH_DURATION_MS]
[--vad_max_speech_duration_s VAD_MAX_SPEECH_DURATION_S]
[--vad_min_silence_duration_ms VAD_MIN_SILENCE_DURATION_MS]
[--vad_speech_pad_ms VAD_SPEECH_PAD_MS]
[--vad_window_size_samples VAD_WINDOW_SIZE_SAMPLES]
[--vad_method {silero_v3,silero_v4,pyannote_v3,pyannote_onnx_v3,auditok,webrtc}]
[--vad_dump] [--vad_device VAD_DEVICE]
[--nullify_non_speech]
[--max_new_tokens MAX_NEW_TOKENS]
[--chunk_length CHUNK_LENGTH]
[--compute_type {default,auto,int8,int8_float16,int8_float32,int8_bfloat16,int16,float16,float32,bfloat16}]
[--batch_recursive] [--beep_off] [--skip]
[--checkcuda] [--print_progress] [--postfix]
[--check_files] [--PR163_off]
[--hallucinations_list_off] [--alt_writer_off]
[--one_word {0,1,2}] [--sentence] [--standard]
[--standard_asia] [--max_comma MAX_COMMA]
[--max_comma_cent {20,30,40,50,60,70,80,90,100}]
[--max_gap MAX_GAP]
[--max_line_width MAX_LINE_WIDTH]
[--max_line_count MAX_LINE_COUNT]
[--min_dist_to_end {0,4,5,6,7,8,9,10,11,12}]
[--prompt_max {16,32,64,128,223}]
[--reprompt {0,1,2}]
[--prompt_reset_on_no_end {0,1,2}] [--ff_dump]
[--ff_track {1,2,3,4,5,6}] [--ff_fc] [--ff_mp3]
[--ff_sync] [--ff_rnndn_sh] [--ff_rnndn_xiph]
[--ff_fftdn [0 - 97]] [--ff_tempo [0.5 - 2.0]]
[--ff_gate] [--ff_speechnorm] [--ff_loudnorm]
[--ff_silence_suppress noise duration]
[--ff_lowhighpass] [--ff_mdx_kim2]
[--mdx_chunk MDX_CHUNK]
[--mdx_device MDX_DEVICE]
[--diarize {pyannote_v3.0,pyannote_v3.1,reverb_v1,reverb_v2}]
[--diarize_device DIARIZE_DEVICE]
[--diarize_threads DIARIZE_THREADS]
[--diarize_dump] [--speaker SPEAKER]
[--num_speakers NUM_SPEAKERS]
[--min_speakers MIN_SPEAKERS]
[--max_speakers MAX_SPEAKERS]
audio [audio ...]
2024-12-20 09:49:54 - faster_whisper - ERROR - faster-whisper-xxl.exe: error: ambiguous option: --prompt could match --prompt_reset_on_temperature, --prompt_max, --prompt_reset_on_no_end
Faster Whisper 返回值: 2
2024-12-20 09:49:55 - faster_whisper - ERROR - Faster Whisper 错误: faster-whisper-xxl.exe: error: ambiguous option: --prompt could match --prompt_reset_on_temperature, --prompt_max, --prompt_reset_on_no_end
2024-12-20 09:49:55 - transcript_thread - ERROR - 转录过程中发生错误: faster-whisper-xxl.exe: error: ambiguous option: --prompt could match --prompt_reset_on_temperature, --prompt_max, --prompt_reset_on_no_end
Traceback (most recent call last):
  File "D:\VideoCaptioner\app\core\thread\transcript_thread.py", line 130, in run
    asr_data = self.asr.run(callback=self.progress_callback)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\VideoCaptioner\app\core\bk_asr\BaseASR.py", line 73, in run
    resp_data = self._run(callback, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\VideoCaptioner\app\core\bk_asr\FasterWhisperASR.py", line 208, in _run
    raise RuntimeError(error_msg)
RuntimeError: faster-whisper-xxl.exe: error: ambiguous option: --prompt could match --prompt_reset_on_temperature, --prompt_max, --prompt_reset_on_no_end
```

**Comment by SlippyJimmy** [comment]
下面的是api的log日志
```
===========转录任务开始===========
时间：2024-12-20 13:38:24.022223
开始转换音频
转换为音频执行命令: ffmpeg -i W:\AI\nakama\part2\Integrating Nakama Into Godot 4.2 Groups Chats and Web OH MY! Part 2.mp4 -map 0:a -ac 1 -ar 16000 -af aresample=async=1 -y Y:\Parallels\Windows10 Software\VideoCaptioner\work-dir\Integrating Nakama Into Godot 4.2 Groups Chats and Web OH MY! Part 2\【Audio】Integrating Nakama Into Godot 4.2 Groups Chats and Web OH MY! Part 2.wav
开始语音转录
初始化 WhisperASR: model=openai/whisper-large-v3-turbo, language=en, prompt=Godot Nakama game docker
开始识别音频...
2024-12-20 14:09:36 - whisper_api - ERROR - 音频识别失败: Error code: 500 - {'message': 'Internal server error'}
Traceback (most recent call last):
  File "Y:\Parallels\Windows10 Software\VideoCaptioner\app\core\bk_asr\WhisperAPI.py", line 80, in _submit
    completion = self.client.audio.transcriptions.create(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Y:\Parallels\Windows10 Software\VideoCaptioner\runtime\Lib\site-packages\openai\resources\audio\transcriptions.py", line 188, in create
    return self._post(  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Y:\Parallels\Windows10 Software\VideoCaptioner\runtime\Lib\site-packages\openai\_base_client.py", line 1278, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Y:\Parallels\Windows10 Software\VideoCaptioner\runtime\Lib\site-packages\openai\_base_client.py", line 955, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "Y:\Parallels\Windows10 Software\VideoCaptioner\runtime\Lib\site-packages\openai\_base_client.py", line 1000, in _request
    return self._retry_request(
           ^^^^^^^^^^^^^^^^^^^^
  File "Y:\Parallels\Windows10 Software\VideoCaptioner\runtime\Lib\site-packages\openai\_base_client.py", line 1093, in _retry_request
    return self._request(
           ^^^^^^^^^^^^^^
  File "Y:\Parallels\Windows10 Software\VideoCaptioner\runtime\Lib\site-packages\openai\_base_client.py", line 1015, in _request
    return self._retry_request(
           ^^^^^^^^^^^^^^^^^^^^
  File "Y:\Parallels\Windows10 Software\VideoCaptioner\runtime\Lib\site-packages\openai\_base_client.py", line 1093, in _retry_request
    return self._request(
           ^^^^^^^^^^^^^^
  File "Y:\Parallels\Windows10 Software\VideoCaptioner\runtime\Lib\site-packages\openai\_base_client.py", line 1059, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.InternalServerError: Error code: 500 - {'message': 'Internal server error'}
2024-12-20 14:09:36 - transcript_thread - ERROR - 转录过程中发生错误: Error code: 500 - {'message': 'Internal server error'}
Traceback (most recent call last):
  File "Y:\Parallels\Windows10 Software\VideoCaptioner\app\core\thread\transcript_thread.py", line 130, in run
    asr_data = self.asr.run(callback=self.progress_callback)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Y:\Parallels\Windows10 Software\VideoCaptioner\app\core\bk_asr\BaseASR.py", line 73, in run
    resp_data = self._run(callback, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Y:\Parallels\Windows10 Software\VideoCaptioner\app\core\bk_asr\WhisperAPI.py", line 54, in _run
    return self._submit()
           ^^^^^^^^^^^^^^
  File "Y:\Parallels\Windows10 Software\VideoCaptioner\app\core\bk_asr\WhisperAPI.py", line 93, in _submit
    raise e
  File "Y:\Parallels\Windows10 Software\VideoCaptioner\app\core\bk_asr\WhisperAPI.py", line 80, in _submit
    completion = self.client.audio.transcriptions.create(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Y:\Parallels\Windows10 Software\VideoCaptioner\runtime\Lib\site-packages\openai\resources\audio\transcriptions.py", line 188, in create
    return self._post(  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Y:\Parallels\Windows10 Software\VideoCaptioner\runtime\Lib\site-packages\openai\_base_client.py", line 1278, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Y:\Parallels\Windows10 Software\VideoCaptioner\runtime\Lib\site-packages\openai\_base_client.py", line 955, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "Y:\Parallels\Windows10 Software\VideoCaptioner\runtime\Lib\site-packages\openai\_base_client.py", line 1000, in _request
    return self._retry_request(
           ^^^^^^^^^^^^^^^^^^^^
  File "Y:\Parallels\Windows10 Software\VideoCaptioner\runtime\Lib\site-packages\openai\_base_client.py", line 1093, in _retry_request
    return self._request(
           ^^^^^^^^^^^^^^
  File "Y:\Parallels\Windows10 Software\VideoCaptioner\runtime\Lib\site-packages\openai\_base_client.py", line 1015, in _request
    return self._retry_request(
           ^^^^^^^^^^^^^^^^^^^^
  File "Y:\Parallels\Windows10 Software\VideoCaptioner\runtime\Lib\site-packages\openai\_base_client.py", line 1093, in _retry_request
    return self._request(
           ^^^^^^^^^^^^^^
  File "Y:\Parallels\Windows10 Software\VideoCaptioner\runtime\Lib\site-packages\openai\_base_client.py", line 1059, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.InternalServerError: Error code: 500 - {'message': 'Internal server error'}
```

**Comment by WEIFENG2333** [comment]
现版本 prompt 填入会有错误，你先不要在这里填东西。

**Comment by SlippyJimmy** [comment]
好的，多谢解答

**Comment by camille3344520** [comment]
尝试修改\app\core\bk_asr\FasterWhisperASR.py后不会有prompt报错



import os
import re
import shutil
import subprocess
from pathlib import Path
import tempfile
from typing import Optional, List, Union

from .ASRData import ASRDataSeg, from_srt
from .BaseASR import BaseASR
from ..utils.logger import setup_logger
from ...config import MODEL_PATH, BIN_PATH


logger = setup_logger("faster_whisper")


class FasterWhisperASR(BaseASR):
    def __init__(self, 
                 audio_path: str,
                 faster_whisper_path: str,
                 whisper_model: str,
                 model_dir: str,
                 language: str = "zh",
                 device: str = "cpu",
                 output_dir: str = None,
                 output_format: str = "srt",
                 use_cache: bool = False,
                 need_word_time_stamp: bool = False,
                 # VAD 相关参数
                 vad_filter: bool = True,
                 vad_threshold: float = 0.4,
                 vad_method: str = "",  # https://github.com/Purfview/whisper-standalone-win/discussions/231
                 # 音频处理
                 ff_mdx_kim2: bool = False,
                 # 文本处理参数
                 one_word: int = 0,
                 sentence: bool = False,
                 max_line_width: int = 100,
                 max_line_count: int = 1,
                 max_comma: int = 20,
                 max_comma_cent: int = 50,
                 prompt: str = None,
                 ):
        super().__init__(audio_path, False)
        
        # 基本参数
        self.model_path = whisper_model
        self.model_dir = model_dir
        self.faster_whisper_path = Path(faster_whisper_path)
        self.need_word_time_stamp = need_word_time_stamp
        self.language = language
        self.device = device
        self.output_dir = output_dir
        self.output_format = output_format
        
        # VAD 参数
        self.vad_filter = vad_filter
        self.vad_threshold = vad_threshold
        self.vad_method = vad_method
        
        # 音频处理参数
        self.ff_mdx_kim2 = ff_mdx_kim2
        
        # 文本处理参数
        self.one_word = one_word
        self.sentence = sentence
        self.max_line_width = max_line_width
        self.max_line_count = max_line_count
        self.max_comma = max_comma
        self.max_comma_cent = max_comma_cent
        self.prompt = prompt

        self.process = None

    def _build_command(self, audio_path: Path) -> List[str]:
        """构建命令行参数"""
        cmd = [
            str(self.faster_whisper_path),
            "-m", str(self.model_path),
            # "--verbose", "true",
            "--print_progress"
        ]
        
        # 添加模型目录参数
        if self.model_dir:
            cmd.extend(["--model_dir", str(self.model_dir)])
        
        # 基本参数
        cmd.extend([
            str(audio_path),
            "-l", self.language,
            "-d", self.device,
            "--output_format", self.output_format,
        ])
        
        # 输出目录
        if self.output_dir:
            cmd.extend(["-o", str(self.output_dir)])
        else:
            cmd.extend(["-o", "source"])

        # VAD 相关参数
        if self.vad_filter:
            cmd.extend([
                "--vad_filter", "true",
                "--vad_threshold", f"{self.vad_threshold:.2f}",
            ])
            if self.vad_method:
                cmd.extend(["--vad_method", self.vad_method])

        # 人声分离
        if self.ff_mdx_kim2 and self.faster_whisper_path.name.startswith("faster-whisper-xxl"):
            cmd.append("--ff_mdx_kim2")

        # 文本处理参数
        if self.one_word:
            self.one_word = 1
        else:
            self.one_word = 0
        if self.one_word in [0, 1, 2]:
            cmd.extend(["--one_word", str(self.one_word)])
        
        if self.sentence:
            cmd.extend([
                "--sentence",
                "--max_line_width", str(self.max_line_width),
                "--max_line_count", str(self.max_line_count),
                "--max_comma", str(self.max_comma),
                "--max_comma_cent", str(self.max_comma_cent)
            ])
        
        # 提示词
        if self.prompt:
            cmd.extend(["--initial_prompt", self.prompt]) # 确保只有 initial_prompt

        return cmd

    def _make_segments(self, resp_data: str) -> list[ASRDataSeg]:
        asr_data = from_srt(resp_data)
        # 过滤掉纯音乐标记
        filtered_segments = []
        for seg in asr_data.segments:
            text = seg.text.strip()
            if not (text.startswith('【') or 
                   text.startswith('[') or 
                   text.startswith('(') or 
                   text.startswith('（')):
                filtered_segments.append(seg)
        return filtered_segments

    def _run(self, callback=None) -> str:
        if callback is None:
            callback = lambda x, y: None

        temp_dir = Path(tempfile.gettempdir()) / "bk_asr"
        temp_dir.mkdir(parents=True, exist_ok=True)

        with tempfile.TemporaryDirectory(dir=temp_dir) as temp_path:
            temp_dir = Path(temp_path)
            wav_path = temp_dir / "audio.wav"
            output_path = wav_path.with_suffix(".srt")

            shutil.copy2(self.audio_path, wav_path)

            cmd = self._build_command(wav_path)

            logger.info("Faster Whisper 执行命令: %s", " ".join(cmd))
            callback(5, "Whisper识别")
            
            self.process = subprocess.Popen(
                cmd,
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
                text=True,
                encoding='utf-8',
                errors='ignore',
                creationflags=subprocess.CREATE_NO_WINDOW if os.name == 'nt' else 0
            )

            is_finish = False
            error_msg = ""

            # 实时打印日志和错误输出
            while self.process.poll() is None:
                output = self.process.stdout.readline()
                output = output.strip()
                if output:
                    # 解析进度百分比
                    if match := re.search(r'(\d+)%', output):
                        progress = int(match.group(1))
                        if progress == 100:
                            is_finish = True
                        mapped_progress = int(5 + (progress * 0.9))
                        callback(mapped_progress, f"{mapped_progress} %")
                    if "error" in output:
                        error_msg += output
                        logger.error(output)
                    else:
                        logger.info(output)

            # 获取所有输出和错误信息
            self.process.communicate()

            logger.info("Faster Whisper 返回值: %s", self.process.returncode)
            if not is_finish:
                logger.error("Faster Whisper 错误: %s", error_msg)
                raise RuntimeError(error_msg)
            
            # 判断是否识别成功
            if not output_path.exists():
                raise RuntimeError(f"Faster Whisper 输出文件不存在: {output_path}")

            logger.info("Faster Whisper 识别完成")
    
            callback(100, "识别完成")

            return output_path.read_text(encoding='utf-8')

    def _get_key(self):
        return f"{self.__class__.__name__}-{self.crc32_hex}-{self.need_word_time_stamp}-{self.model_path}-{self.language}"
