### ISSUE TITLE
想问下软件里的葡萄牙语是否是直接包含了巴西葡萄牙语

### ISSUE THREAD

**Issue by acai884** [WEIFENG2333/VideoCaptioner#184]
### 🤔 问题描述 Problem Description

RT

**Comment by asp3000** [comment]
如果是语言转录的话，你得看模型，Large的应该是有，tiny的肯定是没有

**Comment by WEIFENG2333** [comment]
这个不清楚具体whispe的训练数据是怎么样的，得要你实际测试。
