### ISSUE TITLE
字幕无法压制进视频

### ISSUE THREAD

**Issue by exhaustivity** [WEIFENG2333/VideoCaptioner#188]
### 问题描述 | Problem Description

由1.1.1更新到1.2.0后，字幕无法压制进视频

**Comment by WEIFENG2333** [comment]
是不是在设置页面开启了软字幕？

```
硬字幕是嵌入视频的，软字幕是外挂的。

**Comment by exhaustivity** [comment]
确实是软字幕的原因，但现在有个新的问题：手动选择的字幕合成出来是没有修改过的样式的，只有一整趟流程跑下来的才有
![屏幕截图 2024-12-26 201749](https://github.com/user-attachments/assets/5ca75a88-badb-4e64-8164-316a03324fad)
![屏幕截图 2024-12-26 201949](https://github.com/user-attachments/assets/47556b8a-7154-479b-8289-8aaaaf6e6d40)

**Comment by philpw99** [comment]
MP4软字幕的格式是MOV_TEXT，是没有任何格式的，如果要合成有格式的软字幕，就必须先用MKVTOOLNIX把MP4转成MKV

**Comment by exhaustivity** [comment]
视频转换为.mkv后硬字幕依然是没有样式
![image](https://github.com/user-attachments/assets/836f5558-a592-4d98-9f61-87275491b0f8)
![image](https://github.com/user-attachments/assets/59aebd46-c75a-460e-b944-7fe08f96297e)
而软字幕会直接报错
![image](https://github.com/user-attachments/assets/25f63ccf-fad7-44e4-ad13-afce3642923a)
字幕文件在MKVTOOLNIX中只能转换为.mks格式，且无法在卡卡字幕选择中选中
![image](https://github.com/user-attachments/assets/f1538c6c-51e0-4c82-befc-0cd463818fdc)

**Comment by WEIFENG2333** [comment]
`str`格式的字幕本来就是纯文本，不含样式的。`ass`格式才是含样式的字幕。

如果你是想获得含样式的外挂字幕，可以在软件里面导入你的SRT字幕然后以`ass`格式导出，导出后的字幕就会包含你在软件设置的样式了。
![PixPin_2024-12-27_16-42-16](https://github.com/user-attachments/assets/d33a78d4-3ae4-459d-a132-97a220ee1dea)

**Comment by exhaustivity** [comment]
解决了，谢谢各位的解答
