### ISSUE TITLE
大佬您好，请教一下今天更新修复的bug，打包版如何更新呢？

### ISSUE THREAD

**Issue by ganen1933** [WEIFENG2333/VideoCaptioner#19]
### 🤔 问题描述 Problem Description

大佬您好，请教一下今天更新修复的bug，打包版如何更新呢？好像还是1.0.0版本的

**Comment by WEIFENG2333** [comment]
这两天将会持续收集反馈，整理完后将统一在软件推送更新。

届时打开软件就可以看到更新提示。
