### ISSUE TITLE
問題&建議

### ISSUE THREAD

**Issue by cs064857** [WEIFENG2333/VideoCaptioner#2]
問題：
1、視頻總共8分鐘，使用B接口、J接口轉錄後出來的【原始字幕】B 接口.srt也有8分鐘，但是為何【优化字幕】result.ass、【优化字幕】result_智能断句.srt這兩個只有5分40秒的內容?我試了三次都差不多是這個結果。而用本地Whisper large v2來跑就正常沒這個問題。

建議：
1、若上傳的是mp3等純音頻的話，能將音頻轉為視頻再進行字幕合成嗎?不然最後合成出來的是mp3，看不到字幕

2、請問能提供自定義提示詞嗎，比如說可以設定成翻譯為學術風格或者加入破限提示詞之類的?

**Comment by WEIFENG2333** [comment]
1.由于程序设置了缓存，所以说即使你调用了3次后面两次会使用缓存得到一样的结果。
猜测原因是程序大模型公益接口较多人使用，并不稳定，请求错误然后会有错漏。不过还是建议配置自己的OpenAI接口，使用更强大的模型。
后续会优化相关逻辑。

2.转换出来有字幕文件的，直接把字幕文件拖到你的音频播放器就可以查看了。转换成视频其实没有什么必要。

3.自定義提示詞是一个不错的功能，后续会加上的。

谢谢你的建议。

**Comment by WEIFENG2333** [comment]
已经实现自定義提示詞，通过提供正确的文稿或者部分的参考内容，翻译或者优化质量都能进一步有所改善。

下个版本将推送更新。

![PixPin_2024-11-16_23-59-45](https://github.com/user-attachments/assets/706b62af-f9d4-47da-bff9-62e9ec578311)

![PixPin_2024-11-16_23-59-18](https://github.com/user-attachments/assets/a96d2443-d78a-45db-bda5-f9e31ef27ace)
