### ISSUE TITLE
经常有字幕中的某一句会翻译解释出一大串文字内容

### ISSUE THREAD

**Issue by ganen1933** [WEIFENG2333/VideoCaptioner#20]
### 问题描述 | Problem Description

大佬辛苦啦，这应该是提示词有问题吧。

比如SRT字幕中的这一句：白居易作诗的章法文理
这一句翻译输出的内容是：White Egret's Poetic Composition and Literary StyleIn the realm of Chinese poetry, Bai Juyi (白居易) is renowned for his distinctive approach to poetic structure and literary composition. His writing style is characterized by clarity, directness, and a remarkable ability to convey complex emotions and social observations through accessible language. Bai Juyi's poems typically feature a straightforward narrative flow, avoiding overly ornate or obscure expressions.His poetic structure often follows the regulated verse (律诗) and ancient-style poetry (古诗) formats, with a strong emphasis on rhythm and musicality. Bai Juyi was particularly skilled at creating poems that could be easily understood and appreciated by a wide audience, including common people, which was somewhat revolutionary for his time.The literary principles underlying his work include:1. Simplicity and clarity of language2. Strong narrative elements3. Social commentary and emotional depth4. Melodic and rhythmic composition5. Universal themes that resonate with readersBai Juyi's approach to poetry represented a significant departure from the more complex and esoteric styles of his contemporaries, making his work both innovative and widely influential in Chinese literary history.

**Comment by WEIFENG2333** [comment]
模型不够聪明导致的，你是直接用的自带的公益模型吗?

**Comment by ganen1933** [comment]
用的是最新的claude-3-5-haiku模型哦，在其它程序翻译没有类似的情况

**Comment by WEIFENG2333** [comment]
多次重试都是这样吗？

**Comment by ganen1933** [comment]
是的，多次翻译测试还是一样的，上传了测试字幕文件，您测试看看
[测试01.srt.txt](https://github.com/user-attachments/files/17793040/01.srt.txt)

**Comment by WEIFENG2333** [comment]
![PixPin_2024-11-18_09-50-48](https://github.com/user-attachments/assets/0eb747aa-65e1-412b-99df-93cc4efe1b1e)

我尝试了很多次，仍然买一遇到你的问题，模型也是用的 `claude-3-5-haiku-20241022`，包括一些其他模型也试过，但是翻译完全没有问题。

**Comment by ganen1933** [comment]
第13行后面还有个呢，您加上呢试试

**Comment by WEIFENG2333** [comment]
> 第13行后面还有个呢，您加上呢试试

![PixPin_2024-11-18_13-09-03](https://github.com/user-attachments/assets/afd2dc32-0d0a-4ccc-9656-7eeb29b96417)
