### ISSUE TITLE
样式设置不起效果

### ISSUE THREAD

**Issue by wangjianjun0730** [WEIFENG2333/VideoCaptioner#206]
### 问题描述 | Problem Description

![image](https://github.com/user-attachments/assets/c080c971-1905-4c63-9837-ae02a099b955)
![image](https://github.com/user-attachments/assets/203d63f3-ce9e-4b97-8ea5-12d7dcb9983a)

设置样式不起效果

**Comment by WEIFENG2333** [comment]
是否是开了软字幕，软字幕相当于是外挂到视频中的，没有样式的。

**Comment by wangjianjun0730** [comment]
确认如此，我关闭了软字母就好了，不过会有重叠字幕，是我哪里设置有问题么
![39426863cad488929722242593b62f2](https://github.com/user-attachments/assets/cdeae211-052a-4619-bf12-adae05140a02)

**Comment by philpw99** [comment]
重叠字幕的现象，说明你已经把视频和字幕硬合成了，视频里面已经带有字幕的影像，无法消除。
你需要把旧的视频拿出来，和生成的软字幕 .ass 放在一起，就不会有双字幕，而且可以看到字幕的样式了。

**Comment by wangjianjun0730** [comment]
每次使用的应该是没字幕的视频文件，我稍晚一点再试试看😂

**Comment by WEIFENG2333** [comment]
> 每次使用的应该是没字幕的视频文件，我稍晚一点再试试看😂

应该是你播放器自动加载外挂字幕了吧，如果视频目录有同名的字幕文件就会播放器自动加载字幕。但其实是本地播放有效，你去播放器吧外挂的字幕关闭或者把同名的字幕文件移走就行。

**Comment by wangjianjun0730** [comment]
关掉播放器字幕就行，感谢！
