### ISSUE TITLE
 在 mac 电脑上下载本地模型错误

### ISSUE THREAD

**Issue by chinaxxren** [WEIFENG2333/VideoCaptioner#22]
### 问题描述 | Problem Description

<img width="888" alt="image" src="https://github.com/user-attachments/assets/849500b4-2cd1-460c-8af8-57f5984e7715">

**Comment by WEIFENG2333** [comment]
实际上，关于本地运行whisper模型的功能都不可以用。

即使模型下载成功，也无法运行，因为软件里的whisper程序是只有Window的

**Comment by philpw99** [comment]
Mac 安装包出来了，不过还是需要预先安装 Homebrew, aria2, ffmpeg 和 whisper.cpp

https://github.com/philpw99/VideoCaptioner/releases/tag/v1.2.0_3.5.2_M1_Mac
