### ISSUE TITLE
gpt-4o和gpt-4o-mini模型收费贵，改为3.5行不行？

### ISSUE THREAD

**Issue by renzaoren18hao** [WEIFENG2333/VideoCaptioner#24]
### 🤔 问题描述 Problem Description

我在淘宝找到了gpt-4o包天的，改不了也无所谓了*

**Comment by WEIFENG2333** [comment]
现在大模型接口都是白菜价了，你要换gpt-3.5自己去设置里面填你的模型就可以了。

不得不提醒一下：这年头谁还用3.5？性能不如gpt-4o-mini，价格还比这个贵。而且视频翻译消耗的token不多，你翻译个10分钟的视频也就几分钱。软件也已经自带的`gpt-4o-mini`公益接口。

还有，为什么淘宝找到gpt-4o包天的？你买的是API吗？？？

如果不清楚这些建议使用国内厂商的模型，例如[SiliconCloud](https://cloud.siliconflow.cn/i/HF95kaoz)，可以参考 [配置](https://github.com/WEIFENG2333/VideoCaptioner/blob/master/docs/%E9%85%8D%E7%BD%AE.md)

**Comment by renzaoren18hao** [comment]
好的
