### ISSUE TITLE
windows下载模型失败

### ISSUE THREAD

**Issue by 6-Pikachu-9** [WEIFENG2333/VideoCaptioner#25]
### 问题描述 | Problem Description

无法下载模型到本地
![image](https://github.com/user-attachments/assets/31c51a8c-8180-4e01-b83d-aff21c2c810e)

**Comment by WEIFENG2333** [comment]
提交issure前请先搜索  #21    #13 

下个版本推送更新修复。
现在临时解决方案是将程序解压到非中文路径即可。
