### ISSUE TITLE
繁體中文環境的應用需求

### ISSUE THREAD

**Issue by javalee0328** [WEIFENG2333/VideoCaptioner#28]
### 问题描述 | Problem Description

測試了幾個重點，看可以不可以完善：
1.繁體中文即使設置了，也仍然輸出簡體中文
界面
![image](https://github.com/user-attachments/assets/89e6afed-3bb3-4930-be5c-9a53c8496f17)
目標語言
![image](https://github.com/user-attachments/assets/4492538a-9269-401d-a269-822bcd8c1a7b)
2.字幕的位置不能自定義
3.讀取及輸出視頻格式支持廣電格式，如TS、MXF等
4.可否合作開發運用於廣電行業：我的電郵jerry.lee@eracom.com.tw李陳熹

**Comment by WEIFENG2333** [comment]
1. 预料之中的结果，因为尽力有限，暂时有英语和简中的翻译。后续会逐渐加上的。
2. 字幕的位置设置，这个是一个已经完成的功能，下版本更新。 #23
3. 后续会添加更多的视频支持。但本软件主要的功能还是字幕的生成和处理。只提供基本的视频合成功能。建议还是导出字幕后用专业的剪辑软件来弄。
4. 可以联系邮箱：bkfeng@duck.com

**Comment by Photowalk** [comment]
恰恰相反，我要求输出简体，却一直是输出的繁体。

**Comment by WEIFENG2333** [comment]
> 恰恰相反，我要求输出简体，却一直是输出的繁体。

他这里说的是软件的界面语言。
