### ISSUE TITLE
出现错误：4294967274

### ISSUE THREAD

**Issue by tiktol** [WEIFENG2333/VideoCaptioner#3]
### 问题描述 Problem Description

![no](https://github.com/user-attachments/assets/523bd45e-0793-419a-ba3f-e220a7cdbdef)

油管下的一个韩文视频，最后一步出现这个错误，英语视频没有问题
另外可否加入deepseek的API

**Comment by WEIFENG2333** [comment]
1. 方便给一下YouTube链接吗？我看看能不能复现，我测试了许多视频在我的设备没遇到过这样的情况。

2. 程序是是支持deepseek的，你在设置里面填入deepseek的 API Base 和 Key 就可以了。模型填写 deepseek-coder

具体参考官方文档: http://api-docs.deepseek.com/zh-cn/

**Comment by tiktol** [comment]
视频链接：https://www.youtube.com/watch?v=OZvWvPTd8ew

再一个BUG：完成一个视频后，返回到视频创建处，叉掉文件筐的内容，再点击后面的文件导入图标，软件会自动退出

**Comment by WEIFENG2333** [comment]
字幕合成失败时因为韩语路径的支持有一点问题

另外发现Youtube下载字幕的语言部分视频不准确

以上问题均已经修复，程序下个推送版本将更新。
