### ISSUE TITLE
输入url提取视频软件闪退

### ISSUE THREAD

**Issue by yangbuyiya** [WEIFENG2333/VideoCaptioner#31]
### 问题描述 | Problem Description

Windows环境，下载下来了就是软件闪退了

**Comment by yangbuyiya** [comment]
![image](https://github.com/user-attachments/assets/a4669604-386f-405b-9cf3-92665fdc653c)
![image](https://github.com/user-attachments/assets/90d8af82-4b56-464c-a3a4-fd90e2ae9ef4)

**Comment by WEIFENG2333** [comment]
能不能提供视频链接？

**Comment by WEIFENG2333** [comment]
新版本已经更新：https://github.com/WEIFENG2333/VideoCaptioner/releases
