### ISSUE TITLE
软件真不错咧，一人血书Mac版！！

### ISSUE THREAD

**Issue by THREECATSSS** [WEIFENG2333/VideoCaptioner#33]
### 💡 预期的功能 | Expected Feature

如题，一人血书跪求大大出个Mac版，感觉自媒体用mac的还蛮多的，然后很多人跟我一样不会配置python，求大大出个Mac打包程序...祝大大学业顺利

**Comment by WEIFENG2333** [comment]
很遗憾，虽然也很想为Mac用户适配打包。可惜我没有Mac😥 无法打包，难以保证Mac可用。

**Comment by Ainner** [comment]
Mac 启动项目后目前会出现一些错误
1. 无法下载模型
2. 无法通过 URL 直接下载视频

**Comment by WEIFENG2333** [comment]
> Mac 启动项目后目前会出现一些错误
> 
> 1. 无法下载模型
> 2. 无法通过 URL 直接下载视频

预料之中的情况，因为改项目下载使用win的exe程序，whisper也是基于exe的，在mac上无法使用。

**Comment by THREECATSSS** [comment]
好滴好滴，anyway，大大辛苦~

**Comment by philpw99** [comment]
安装包出来了，不过还是需要预先安装 Homebrew, aria2, ffmpeg 和 whisper.cpp

https://github.com/philpw99/VideoCaptioner/releases/tag/v1.2.0_3.5.2_M1_Mac

又或者看看这个教程：
https://github.com/WEIFENG2333/VideoCaptioner/discussions/363

**Comment by RuomuXu** [comment]
> Mac 安装包出来了，不过还是需要预先安装 Homebrew, aria2, ffmpeg 和 whisper.cpp
> 
> https://github.com/philpw99/VideoCaptioner/releases/tag/v1.2.0_3.5.2_M1_Mac
> 
> 又或者看看这个教程： [#363](https://github.com/WEIFENG2333/VideoCaptioner/discussions/363)

按照教程 M2 跑起来了 👍
