### ISSUE TITLE
翻译到目标语言只支持11种语言吗？可以增加支持其他更多小语种的吗？

### ISSUE THREAD

**Issue by ganen1933** [WEIFENG2333/VideoCaptioner#38]
### 💡 预期的功能 | Expected Feature

大佬您好，支持的语种比较少，可以增加翻译到其他语言吗，比如阿拉伯语，荷兰语，泰语，等等

**Comment by WEIFENG2333** [comment]
理论whisper支持的语言都支持，只是程序没有列出。

后续会增加。
