### ISSUE TITLE
音乐环节也会被添加字幕

### ISSUE THREAD

**Issue by talentldk** [WEIFENG2333/VideoCaptioner#4]
### 问题描述 Problem Description

我添加了一个视频文件，选择了“tiny”模型进行转录，发现生成的英文字幕中，在多处音乐环节生成了[MUSIC PLAYING] 这样的字幕。
这个音乐是指纯音乐配音，不是唱歌。

这样的效果显然是不合理地，希望可以优化这个效果。

**Comment by WEIFENG2333** [comment]
已经修复代码，过滤掉以【、[、(、（开头的文本。

下个版本将推送该更新该修复。

感谢你的反馈。
