### ISSUE TITLE
优化翻译提示词/支持本地Ollama接口/历史任务管理

### ISSUE THREAD

**Issue by troublebugs** [WEIFENG2333/VideoCaptioner#40]
### 💡 预期的功能 | Expected Feature

- 优化翻译提示词
**理由**：目前字幕翻译（如英译中）还是存在很多直译的结果。看了下[subtitle_config.py](https://github.com/WEIFENG2333/VideoCaptioner/blob/master/app/core/subtitle_processor/subtitle_config.py)下的提示词，建议增加一下**要求AI翻译过程中充分考虑目标翻译语言母语者文化背景**的相关提示词，因为例如英译中过程中，很多英文是倒装句结构，最后被AI直译之后读起来很别扭，而且还有一些俚语，多重含义的词语直接就翻译了字面意识，按照个人经验，要求AI适应目标语言母语者的文化背景进行翻译往往会得到更好的效果。

我自己试着用Cursor自己写了下提示词并修改到文件中，同一测试视频效果能看到相对一些好的改观。当然我只是随便测试了下，没有认真的自己去写。[在这里](https://gist.githubusercontent.com/troublebugs/4d7eedf1f95994c1049c394a7cfc1167/raw/ba113cca7d59775731476b14bae4f0382ed2d843/subtitle_config.py)

- 支持本地Ollama接口调用
- 归档、重命名、删除历史任务（或包含任务相关文件夹和文件）

最后感谢作者的辛苦付出！

**Comment by WEIFENG2333** [comment]
好的 感谢你的反馈。接下来会逐渐优化提示词的。

关于Ollama，我记得他也同时兼容OpenAI格式的，你把地址填入设置里面即可。

**Comment by troublebugs** [comment]
![image](https://github.com/user-attachments/assets/7b084437-2b15-4050-9a58-41780bba7be8)
另外，现在的拆分句子还是有点问题，如图，是用本地Whisper转录的。

**Comment by WEIFENG2333** [comment]
这个版本的whisper是没有在llm处理时没有进行断句处理的。

新版本已增加断句功能。等待更新推送即可

**Comment by WEIFENG2333** [comment]
> * 要求AI翻译过程中充分考虑目标翻译语言母语者文化背景

关于提示词的问题, 就有关于 Cultural relevance 的表述
```
- Cultural relevance: Appropriately use idioms, proverbs, and modern expressions that fit the target language's cultural background.

```

提示词只是辅助，小模型的话过分强调改观不也算大。想进一步提供翻译质量可以使用Claude-3.5-sonet 等模型会更好。

**Comment by WEIFENG2333** [comment]
优化了相关提示词。优化字幕断句的效果

新版本已经更新：https://github.com/WEIFENG2333/VideoCaptioner/releases
