### ISSUE TITLE
希望增加文稿匹配对齐功能

### ISSUE THREAD

**Issue by henjicc** [WEIFENG2333/VideoCaptioner#41]
### 💡 预期的功能 | Expected Feature

大佬你好呀，希望增加文稿匹配对齐功能，也就是将输入的文稿和视频语音进行对齐。
输入的文稿每一行一句话，也就是一句字幕，在调用 Whisper 识别音频后，将识别结果与输入文稿进行对齐，字幕内容以输入的文稿为准，具体就是类似于剪映中的“文稿匹配”。

最后再次感谢大佬开发的软件，真的非常棒！

**Comment by WEIFENG2333** [comment]
#17 

已经实现，等待新版发布即可。

**Comment by henjicc** [comment]
> #17
> 
> 已经实现，等待新版发布即可。

太棒了！

**Comment by mrzj110** [comment]
> #17
> 
> 已经实现，等待新版发布即可。

催更，急需这个新功能，做视频要搞字幕剪影只能5000字很麻烦
