### ISSUE TITLE
Mac M1 检测LLM功能报错

### ISSUE THREAD

**Issue by alpaca121** [WEIFENG2333/VideoCaptioner#43]
### 问题描述 | Problem Description

没有配置socks代理，点击测试LLM出现一下报错信息，
![000205-20241122-16 18 25zTvh2WCN@2x](https://github.com/user-attachments/assets/17d64ccc-39ab-469d-900e-082a4893ddb1)

**Comment by WEIFENG2333** [comment]
看样子是调用 OpenAI 的库遇到了错误。

尝试在命令行中禁用代理，输入以下三个命令：
```
unset https_proxy; unset http_proxy; unset all_proxy; 
```

因为没有Mac，缺乏对Mac的测试与适配，很难兼顾到这种情况。

**Comment by alpaca121** [comment]
![000206-20241122-16 55 51iW6EeufZ@2x](https://github.com/user-attachments/assets/aba9bb78-0f0b-452f-9315-4ef916e48439)
在合成视频的时候闪退了和CUDA有关吗

**Comment by WEIFENG2333** [comment]
好吧 合成完本来是想打开文件夹的，但Mac不支持这个os.starfilet() 函数就报错。

缺乏设备实在难以调试，问题太多的话还是建议使用 window 运行。

**Comment by philpw99** [comment]
Mac 安装包出来了，不过还是需要预先安装 Homebrew, aria2, ffmpeg 和 whisper.cpp

https://github.com/philpw99/VideoCaptioner/releases/tag/v1.2.0_3.5.2_M1_Mac

试试看这个版本还有没有这样的问题。
