### ISSUE TITLE
建议提供更大的本地模型

### ISSUE THREAD

**Issue by 123yangyan** [WEIFENG2333/VideoCaptioner#44]
### 💡 预期的功能 | Expected Feature

现有的largev2对于长视频断句、识别都有比较大的误差率，是否可以通过更大的模型完成对长视频的分析。还是说可以增加什么插件。

**Comment by WEIFENG2333** [comment]
#15

新版本增加了 largev3
![PixPin_2024-11-23_01-23-45](https://github.com/user-attachments/assets/be6de7c9-84af-43bd-9b26-390b931ee917)
