### ISSUE TITLE
支持更多whisper模型

### ISSUE THREAD

**Issue by exjhon** [WEIFENG2333/VideoCaptioner#45]
### 💡 预期的功能 | Expected Feature

是不是只支持到large-v2，希望支持large-v3，fast whisper，最新的large-v3-turbo

**Comment by Hans-Deng** [comment]
部分满足 https://github.com/WEIFENG2333/VideoCaptioner/issues/44#issuecomment-2494357884

**Comment by WEIFENG2333** [comment]
新版本已经更新
新增 Whisper-v3 模型支持
https://github.com/WEIFENG2333/VideoCaptioner/releases

**Comment by keno-log** [comment]
large-v3-turbo优化非常多，期待尽快支持。谢谢！
