### ISSUE TITLE
Subtitles will not be created for longer than 10 minutes

### ISSUE THREAD

**Issue by SingingDalong** [WEIFENG2333/VideoCaptioner#46]
### 🤔 问题描述 Problem Description

![2024-11-23_031953](https://github.com/user-attachments/assets/422f0a80-d174-41b5-9454-e64587ae6ea4)

Subtitles will not be created for longer than 10 minutes.

The audio source used for testing was 45 minutes. However, the subtitles are created after only about 10 minutes. It's the same for both B and J exits.

**Comment by WEIFENG2333** [comment]
软件检测到已经存在文件名就不再优化处理。

点击 打开文件夹 可以把存在的文件先删掉。

**Comment by WEIFENG2333** [comment]
新版本已经更新：https://github.com/WEIFENG2333/VideoCaptioner/releases
