### ISSUE TITLE
打开srt文件后直接闪退了

### ISSUE THREAD

**Issue by brownplayer** [WEIFENG2333/VideoCaptioner#48]
### 问题描述 | Problem Description

打开srt文件后直接闪退了，我觉得可能是一个bug因为，我有三个srt文件，但只有打开一个的时候不闪退，其他两个都是闪退了。但是有一说一效果很不错。还有就是在优化字幕后，会有一些字幕被吞掉了。

**Comment by WEIFENG2333** [comment]
旧版本的srt文件导入时，可能由于字幕文件并不规范导致识别错误。

新版本已经适配了一些情况，可以正常导入。

新版本也对一些字幕被吞掉的情况有所改善。

**Comment by WEIFENG2333** [comment]
新版本已经更新：https://github.com/WEIFENG2333/VideoCaptioner/releases
