### ISSUE TITLE
转录配置中whisper模型是否支持以api的形式调用

### ISSUE THREAD

**Issue by uxfion** [WEIFENG2333/VideoCaptioner#5]
有时候自己电脑性能不足以带动whipser large，希望可以支持以openai api的形式调用whisper

API文档：https://platform.openai.com/docs/api-reference/audio/createTranslation

这样可以在GPU服务器上分别部署whisper + ollama，然后在瘦客户端上运行该软件。

另外想问一下转录模型中B接口和J接口有什么区别？

**Comment by WEIFENG2333** [comment]
OpenAI Api的格式有计划支持。然后就可以通过 `groq`  或者其他部署的服务来调用语音转文字。

B接口和J接口都是通过网络调用，不保证稳定性，J接口会稍微好于B接口。

**Comment by WEIFENG2333** [comment]
![PixPin_2024-11-20_00-59-36](https://github.com/user-attachments/assets/96ae8787-6b8a-49cc-9e8b-618439c02d25)

功能已经实现
