### ISSUE TITLE
能否新增批量翻译字幕srt文件的功能，不需要先加载视频，而是批量加载srt字幕文件然后再批量翻译

### ISSUE THREAD

**Issue by dajiahao-bit** [WEIFENG2333/VideoCaptioner#50]
### 💡 预期的功能 | Expected Feature

能否新增批量翻译字幕srt文件的功能，不需要先加载视频，而是批量加载srt字幕文件然后再批量翻译

**Comment by WEIFENG2333** [comment]
感觉这个应用场景不是很大，现在只能一个个在“字幕优化与翻译”页面一个个处理。

后续可能视情况添加。
