### ISSUE TITLE
批处理输出文件名都一样，自己覆盖自己

### ISSUE THREAD

**Issue by 3102603916** [WEIFENG2333/VideoCaptioner#51]
### 问题描述 | Problem Description

批处理输出文件名都一样，都是【原始字幕】Whisper[本地].srt
但是批处理输出文件夹又是和原始视频一个位置，如果原始视频都在一个文件夹里，字幕文件会自己覆盖自己，最后只保留一个文件，多个视频白白转换。

**Comment by WEIFENG2333** [comment]
是的，我已经发现了这个问题。

新版本已经改善了文件的命名。等发布后下载新版本就好了。

**Comment by WEIFENG2333** [comment]
新版本已经更新：https://github.com/WEIFENG2333/VideoCaptioner/releases
