### ISSUE TITLE
能否支持Ollama作为本地LLM的服务

### ISSUE THREAD

**Issue by SimFantasy** [WEIFENG2333/VideoCaptioner#52]
### 💡 预期的功能 | Expected Feature

能否支持Ollama作为本地LLM的服务？

**Comment by WEIFENG2333** [comment]
支持Ollama模型，Ollama有兼容OpenAI的格式，填入 `base_url` 就可以。[https://ollama.com/blog/openai-compatibility](https://ollama.com/blog/openai-compatibility)

现在的很多大模型API已经是白菜价。参数量太少的模型效果一般，还是不建议使用。
