### ISSUE TITLE
1.1 无法安装运行

### ISSUE THREAD

**Issue by heragehome** [WEIFENG2333/VideoCaptioner#53]
### 问题描述 | Problem Description

安装成功后点击启动,会有报错
![屏幕截图 2024-11-23 235101](https://github.com/user-attachments/assets/a9a2ea7d-a7cd-42f7-a80c-2db20c58a4ed)

**Comment by WEIFENG2333** [comment]
1. 尝试管理员方式打开
2. 或者尝试卸载后安装到D盘

你看看能不能解决，希望后续的反馈

**Comment by heragehome** [comment]
> 1. 尝试管理员方式打开
> 2. 或者尝试卸载后安装到D盘
> 
> 你看看能不能解决，希望后续的反馈

感谢, 管理员启动成功
这个项目的质量比剪映还要高!
