### ISSUE TITLE
批量处理功能不稳定

### ISSUE THREAD

**Issue by heragehome** [WEIFENG2333/VideoCaptioner#57]
### 问题描述 | Problem Description

J接口功能不稳定,卡在上传
whisper medium功能不稳定,卡在转换大部分[
![屏幕截图 2024-11-24 083632](https://github.com/user-attachments/assets/13335f67-bf40-4db9-887e-5cc113b928c4)
](url)

**Comment by WEIFENG2333** [comment]
J接口是公益接口，不保证稳定性。

卡在转换大部分可能是出现了一些幻觉问题，whisper-cpp不能正常完成全部任务主动退出。下版本将添加Faster-Whisper
