### ISSUE TITLE
RuntimeError: 生成 SRT 文件失败: [WinError 2] 系统找不到指定的文件。

### ISSUE THREAD

**Issue by lige1314520** [WEIFENG2333/VideoCaptioner#58]
Traceback (most recent call last):
  File "C:\Users\Lige\Desktop\VideoCaptioner-master\app\core\thread\transcript_thread.py", line 93, in run
    asr_data = self.asr.run(callback=self.progress_callback)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lige\Desktop\VideoCaptioner-master\app\core\bk_asr\BaseASR.py", line 73, in run
    resp_data = self._run(callback, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lige\Desktop\VideoCaptioner-master\app\core\bk_asr\WhisperASR.py", line 140, in _run
    raise RuntimeError(f"生成 SRT 文件失败: {str(e)}")
RuntimeError: 生成 SRT 文件失败: [WinError 2] 系统找不到指定的文件。
[]

**Comment by PhiFever** [comment]
同样的问题，在设置中指定Whisper[本地]并指定模型为large-v3时出现。

**Comment by techoc** [comment]
检查一下 `VideoCaptioner\resource\bin`文件夹下有没有 `whisper-cpp.exe`
```
d----          2024/11/24    11:23                cpu
-a---           2024/7/27    19:48        5649408 aria2c.exe
-a---           2024/9/30    16:49       87638016 ffmpeg.exe
-a---           2023/7/22    21:09         206336 whisper-cpp.exe
-a---           2023/7/22    21:08         576512 Whisper.dll
```

**Comment by PhiFever** [comment]
> 检查一下 `VideoCaptioner\resource\bin`文件夹下有没有 `whisper-cpp.exe`
> 
> ```
> d----          2024/11/24    11:23                cpu
> -a---           2024/7/27    19:48        5649408 aria2c.exe
> -a---           2024/9/30    16:49       87638016 ffmpeg.exe
> -a---           2023/7/22    21:09         206336 whisper-cpp.exe
> -a---           2023/7/22    21:08         576512 Whisper.dll
> ```

没有，并且似乎github仓库里也没有这些文件，请问我应该在哪里下载这些文件呢？
![image](https://github.com/user-attachments/assets/2f466079-20fe-4aba-8db6-854fde4fedef)

**Comment by techoc** [comment]
卸载了重新安装试一下


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "WEIFENG2333/VideoCaptioner"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月24日(星期天) 晚上7:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [WEIFENG2333/VideoCaptioner] RuntimeError: 生成 SRT 文件失败: [WinError 2] 系统找不到指定的文件。 (Issue #58)





  
检查一下 VideoCaptioner\resource\bin文件夹下有没有 whisper-cpp.exe
 d----          2024/11/24    11:23                cpu -a---           2024/7/27    19:48        5649408 aria2c.exe -a---           2024/9/30    16:49       87638016 ffmpeg.exe -a---           2023/7/22    21:09         206336 whisper-cpp.exe -a---           2023/7/22    21:08         576512 Whisper.dll   
没有，并且似乎github仓库里也没有这些文件，请问我应该在哪里下载这些文件呢？
 image.png (view on web)

**Comment by PhiFever** [comment]
> 卸载了重新安装试一下
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "WEIFENG2333/VideoCaptioner" ***@***.***&gt;; 发送时间:&nbsp;2024年11月24日(星期天) 晚上7:05 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [WEIFENG2333/VideoCaptioner] RuntimeError: 生成 SRT 文件失败: [WinError 2] 系统找不到指定的文件。 (Issue #58) 检查一下 VideoCaptioner\resource\bin文件夹下有没有 whisper-cpp.exe d---- 2024/11/24 11:23 cpu -a--- 2024/7/27 19:48 5649408 aria2c.exe -a--- 2024/9/30 16:49 87638016 ffmpeg.exe -a--- 2023/7/22 21:09 206336 whisper-cpp.exe -a--- 2023/7/22 21:08 576512 Whisper.dll 没有，并且似乎github仓库里也没有这些文件，请问我应该在哪里下载这些文件呢？ image.png (view on web) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

我是git clone下来`python main.py`执行的，看起来这正是问题所在，可能是因为必要的二进制文件在打包时才会被添加进程序目录

**Comment by WEIFENG2333** [comment]
对的源码并没有包含这些二进制文件：
-a---           2024/7/27    19:48        5649408 aria2c.exe
-a---           2024/9/30    16:49       87638016 ffmpeg.exe
-a---           2023/7/22    21:09         206336 whisper-cpp.exe
-a---           2023/7/22    21:08         576512 Whisper.dll

你可以在release 早期的包里面解压，从而获得的里面这些二进制文件（仅限win）  [v1.0.0](https://github.com/WEIFENG2333/VideoCaptioner/releases/tag/v1.0.0)

**Comment by PhiFever** [comment]
我自己编译了一份whisper-cpp，达到了目标效果，感谢帮助。
