### ISSUE TITLE
希望支持批量更正字幕中的错字（例如“他”改为“她”）

### ISSUE THREAD

**Issue by ltzu929** [WEIFENG2333/VideoCaptioner#59]
### 💡 预期的功能 | Expected Feature

您好，感谢您开发了 VideoCaptioner 这样一个优秀的工具！在使用过程中，我发现有时字幕中会存在一些常见错字，例如将“他”错误地写成“她”，或者将小众词汇“呜米”错误地识别为“欧米”。

为了解决这一问题，我希望能增加以下功能：

1. 批量更正错字：通过预设一个词典或规则表，将字幕中的错字批量替换为正确的文字，例如：

将“他”替换为“她”

将“欧米”替换为“呜米”

2. 支持本地模型微调：针对小众词汇或特定领域术语，允许用户通过微调模型进一步提高字幕的准确性，减少类似的错误。

我相信这个功能会对有类似需求的用户非常有帮助。如果需要更详细的需求说明，我也很乐意提供进一步的协助！

期待您的回复，并感谢您的辛勤付出！

**Comment by WEIFENG2333** [comment]
![PixPin_2024-11-24_15-01-56](https://github.com/user-attachments/assets/08de0fae-132a-4a64-ae0c-51ffab28a4de)

可以通过文稿提示来提供你的术语表、原视频字幕文稿、修正要求的任何一种或多种内容。

填写的格式不要求，只需要阐述清晰就可以了。

以下是一种填写参考（三个部分不都需要填写）：
```
# 术语表
他 -> 她
欧米 -> 呜米
打call -> 应援
机器学习 -> Machine Learning
深度学习 -> Deep Learning
孟德尔
在加纳共和国离婚
......

# 原字幕文稿
他今天去看欧米的演唱会真是太开心了，乌米的《在加纳共和国离婚》新歌太棒了我要给她打call，在立本的演唱会上他表现得很好，这次孟德尔用机器学习做了一个新项目。

# 修正要求（格式相关的不用说明，填写内容相关的要求即可）
1. 将人称代词"他"统一修改为"她"
2. 将"欧米"统一修改为"呜米"
3. 将"打call"修改为"应援"
4. 将"机器学习"改为"Machine Learning"
5. 注意人名“孟德尔”
......
```

另外如果你使用参数量较低的LLM大模型，由于小模型的上下文有限，不建议填写过长的内容（几千字这样子的）。
