### ISSUE TITLE
建议加Mac版本和导出字幕

### ISSUE THREAD

**Issue by W1842984353** [WEIFENG2333/VideoCaptioner#60]
### 💡 预期的功能 | Expected Feature

建议加Mac版本，方便在MacMini上使用，耗电低。任务完成后只要导出字幕即可，已经有原视频没必要在导出视频用不到。

**Comment by WEIFENG2333** [comment]
你只需开启软字幕功能就不会继续压制字幕。

**Comment by WEIFENG2333** [comment]
关于Mac版本，没有相关设备确实无能为力。

**Comment by philpw99** [comment]
Mac 安装包出来了，不过还是需要预先安装 Homebrew, aria2, ffmpeg 和 whisper.cpp

https://github.com/philpw99/VideoCaptioner/releases/tag/v1.2.0_3.5.2_M1_Mac
