### ISSUE TITLE
首次打开软件可能出现的问题

### ISSUE THREAD

**Issue by Udll30** [WEIFENG2333/VideoCaptioner#61]
### 问题描述 | Problem Description

首次运行新版（版本v1.1.1）的小伙伴可能会疑惑为什么无法进行下一步，也有可能是我个人的电脑上的缩放导致。
本人电脑信息：Windows 10专业工作站版，1920×1080，100%缩放。
如图所示，只需要把程序的边框拉长后，即可点击“我知道了”进行下一步。
希望作者能注意到这个情况，有的小白可能会觉得疑惑，祝软件越做越好。
![搜狗截图20241124221210](https://github.com/user-attachments/assets/5414c381-b125-4ee1-acd5-77bcf05d0fec)
![搜狗截图20241124221235](https://github.com/user-attachments/assets/7f2e1815-3c3c-40a9-8021-db4403d0edbe)

**Comment by WEIFENG2333** [comment]
哈哈 确实是一个问题 我去把公告该短一段吧。

感谢你的反馈
