### ISSUE TITLE
转录音频大小及长度不正确

### ISSUE THREAD

**Issue by fortunetw** [WEIFENG2333/VideoCaptioner#62]
### 问题描述 | Problem Description

同一个影片
1.0.0版在转录音频时，转录出音频大小为 39.1MB并且长度可见
![1](https://github.com/user-attachments/assets/d69f06c9-627d-4829-a0d1-3ebd2a76eded)
改为1.1.1版本後，转录出音频大小为 14.6MB 长度不可见
![2](https://github.com/user-attachments/assets/4d99a221-c187-4ea9-8bc1-f97560f74fb9)
查阅log，没有错误讯息，但是档案大小是错的，并且字幕档也是只有头尾，中间缺漏。

**Comment by WEIFENG2333** [comment]
发布提供音频文件吗？
