### ISSUE TITLE
希望可以在字幕视频合成阶段加添一个使用GPU的选项, 让用户自主选择使用CPU还是GPU进行合成

### ISSUE THREAD

**Issue by flytilltheend** [WEIFENG2333/VideoCaptioner#65]
### 💡 预期的功能 | Expected Feature

RT, 这样速度上应该也会更快一些.

**Comment by WEIFENG2333** [comment]
会检测是否支持cuda，如果支持的话默认使用GPU。

**Comment by WEIFENG2333** [comment]
你可以在主页里面查看日志
![PixPin_2024-11-25_23-16-35](https://github.com/user-attachments/assets/2ac551ef-1d4d-4a8f-9a9a-993f03513f88)

在合成任务中，支不支持cuda会有说明。

**Comment by hangajEdu** [comment]
使用硬字幕
检查CUDA是否可用
CUDA可用
使用CUDA加速

**Comment by WEIFENG2333** [comment]
那说明软件已经在合成过程已经为ffmpeg提供了gpu加速相关的参数。

至于为什么GPU占用不高，也许是驱动问题，又或者其他问题我也无法确定。
