### ISSUE TITLE
[建议] 多项用户界面及功能建议

### ISSUE THREAD

**Issue by HTT-Solaca** [WEIFENG2333/VideoCaptioner#66]
### 💡 预期的功能 | Expected Feature

1.任务创建后请直接跳转到“语音转录”或者“字母优化与翻译”界面
2.由于重新录视频是一项性能与时间需求较大的工作 特别是当视频文件非常巨大的时候 请务必让用户手动选择是否合成（或者默认为 不合成、仅保留字幕文件）
3.把“字幕优化与翻译“界面中的”开始“按钮意义不明[是开始优化亦或开始合成]
4. 文稿提示功能可以直接拆分为以下三部分：人名指定、背景指定、其他提示 。

**Comment by WEIFENG2333** [comment]
1. 任务创建以后现在本来就是会跳转的呀~
2. 设置里面开启软字幕功能则不会压制视频。几乎没有处理速度。
3. 我认为已经很清晰了，“字幕优化与翻译“界面的按钮就是用来优化和翻译字幕的。
4. 你是说把“文稿提示”分为3个按钮吗？我认为没有必要，你可以在“文稿提示”里面都填入人名指定、背景指定、其他提示 等等内容。资源表述清晰，大模型会理解的。

**Comment by GJG666** [comment]
第二点：开启软字幕就不会硬合成到视频中了，速度非常快

**Comment by GJG666** [comment]
第二点：开启软字幕就不会硬合成到视频中了，速度非常快
