### ISSUE TITLE
为什么本地whisper转写在任务管理器页面显示占用3D而不是cuda?

### ISSUE THREAD

**Issue by Silverwolf-x** [WEIFENG2333/VideoCaptioner#67]
### 🤔 问题描述 Problem Description

如题，whisper-cpp应该也支持cuda吧，可能用的是Vulkan版本？

https://github.com/ggerganov/whisper.cpp?tab=readme-ov-file#nvidia-gpu-support

![image](https://github.com/user-attachments/assets/db288465-c6ea-4390-af2b-2601390f3211)

**Comment by Silverwolf-x** [comment]
> 本来想帮忙提交一个cuda版本的fork，但发现这个cpp与目前v1.7.2的whisper-cpp有太多命令的不同，有点难帮忙（

https://github.com/ggerganov/whisper.cpp/actions/runs/11917875127

**Comment by WEIFENG2333** [comment]
程序使用的Const-me版本的WhisperCpp： https://github.com/Const-me/Whisper
 
主要是因为ggerganov的cuda版本的cpp程序体积大。CPU版本这发挥不出GPU的优势。

为了保证软件的轻量化，于是采用的Const-me优化的版本，同时也支持GPU调用。
