### ISSUE TITLE
希望能添加匯出樣式字幕功能

### ISSUE THREAD

**Issue by brian147258** [WEIFENG2333/VideoCaptioner#69]
### 💡 预期的功能 | Expected Feature

因為字幕總會有誤，需要修修改改，目前的樣式字幕只有在一條龍輸出時，才會生成。希望能在字幕與優化翻譯那邊，添加匯出樣式字幕的選項。感謝。

**Comment by WEIFENG2333** [comment]
你好! 关于导出样式字幕的需求,目前系统已经支持通过 ASS 格式导出字幕。

ASS (Advanced SubStation Alpha) 格式是一种高级字幕格式,它可以:
- 保存完整的字幕样式信息(字体、颜色、位置等)
- 支持动态效果和复杂排版
- 被大多数视频播放器广泛支持

你可以直接在字幕导出选项中选择 ASS 格式来保存带样式的字幕文件。这样导出的字幕会保留所有设置好的样式信息。
