### ISSUE TITLE
我想让生成的字幕文件名和视频文件名保持一致，可以实现吗？

### ISSUE THREAD

**Issue by js79903** [WEIFENG2333/VideoCaptioner#7]
### 💡 预期的功能 | Expected Feature

否则后期处理好麻烦,谢谢

**Comment by WEIFENG2333** [comment]
可以是可以，但是软件处理过程会生成多种字幕（原始生成的、优化翻译后的），重新重命名是为了更好区分。

想让字幕文件名和视频文件名保持一致的目的是什么？如果你是剪辑视频需要的话直接把字幕导入剪辑软件就可以了。

**Comment by js79903** [comment]
我同时处理多个mp4文件,自己学习用的,不用剪辑软件的
首先我会在本地用ffmpeg把整夹的mp4转为mp3,然后再处理
我其实只需要生成同时有中英文的ass这个文件就够了,
其它对我是用不上的
生成的ass文件,我会剪切到之前的mp4文件夹那里
按现在软件的功能,会生成多夹,这样我处理好麻烦
或者能在生成的字幕文件名前或后面加上mp4的档名吗?
这样我能批处理
因为如果全是"【优化字幕】result.ass",
我就没办法批处理了

**Comment by js79903** [comment]
buzz的功能就是这样的

**Comment by WEIFENG2333** [comment]
软件最初也只是打算完成字幕和视频合成功能。至于后处理，每个人的需求不一样，太多方案中就选择简化文件名方便用户区分使用。

接下来会考虑把最终的字幕文件改成与视频名称一致的。

**Comment by leaping365** [comment]
一些视频播放软件，字幕名称和音视频名称一致的时候可以直接调用字幕播放，否则还要手动找字幕。

**Comment by leaping365** [comment]
字幕最好也生成在原始音频或音频的文件夹，否则还要移动。
