### ISSUE TITLE
希望您能考虑增加VAD功能

### ISSUE THREAD

**Issue by wnosos6** [WEIFENG2333/VideoCaptioner#72]
### 💡 预期的功能 | Expected Feature

开发者大佬，我有一个功能请求，希望您能在项目中增加VAD（语音活动检测）功能。当前项目的语音识别基于Whisper，但Whisper普遍存在的幻听问题确实影响了用户体验。在fast-whisper等基于CUDA的项目中，VAD功能已经证明能够有效减少幻听现象。然而，这些项目依赖于CUDA，导致AMD显卡用户无法使用VAD功能。

您的项目一直基于Whisper而非fast-whisper，这对AMD显卡用户来说是一个优势。因此，我希望能在此基础上增加VAD功能，进一步提升识别的准确性和用户体验。

**Comment by WEIFENG2333** [comment]
现在正在制作中...

**Comment by WEIFENG2333** [comment]
已经添加
