### ISSUE TITLE
批量操作的时候仅仅选择生成双语字幕，不需要视频合成。增加Mac版本

### ISSUE THREAD

**Issue by zhaoxiaopeng3** [WEIFENG2333/VideoCaptioner#75]
### 💡 预期的功能 | Expected Feature

感谢能出这么好的软件。希望批量操作的时候仅仅选择生成双语字幕，不需要视频合成。视频合成会很慢，经常只需要生成字幕就好了，请添加这项仅仅导出字幕的功能。如果能批量导出和原来视频一样的名称更好，直接就可以双击打开了。对学习外语视频课程非常有帮助。希望增加Mac版本，很期待。谢谢！

**Comment by WEIFENG2333** [comment]
现版本开启软字幕功能可以解决。新版本会增加开关。

很遗憾，由于没有Mac设备，Mac系统适配和打包的工作我无法完成。

**Comment by zhaoxiaopeng3** [comment]
开启了软字幕还会字幕视频合成，后台文件夹里合成了字幕和视频，加长了不需要的这段时间。如果能关闭自动视频合成就完美了。一套课程，放进去，字幕全出了，配合原来的视频，节省不少时间。             谢谢开发了这么好的产品！

**Comment by WEIFENG2333** [comment]
软字幕处理几乎不消耗时间的

**Comment by philpw99** [comment]
安装包出来了，不过还是需要预先安装 Homebrew, aria2, ffmpeg 和 whisper.cpp
支持直接生成同样名字的字幕，或者自定义前缀或者后缀

https://github.com/philpw99/VideoCaptioner/releases/tag/v1.2.0_3.5.2_M1_Mac
