### ISSUE TITLE
希望能增加Sakura模型作为日语大模型翻译器

### ISSUE THREAD

**Issue by aierlma** [WEIFENG2333/VideoCaptioner#77]
### 💡 预期的功能 | Expected Feature

有关日语视频的制作，转录这一步理论上是可以使用large-v3模型的，但是长视频是不行的，已经有issue提出加入vad可以有效解决该问题，实测确实如此，作者已经提到正在制作，不过应该也可以参考一下[faster-whisper-webui](https://huggingface.co/spaces/aadnk/faster-whisper-webui)。另，我记得之前忘记在哪里看到的一个说法是faster模型处理日语会效果不太好，推荐使用whisper原版模型，实测如此。

希望添加Sakura模型作为后期日语翻译模型，可以更进一步降低成本（纯本地），并且实测，Sakura模型在翻译特定领域的日文文本会比gpt-4o更加符合中文的语气和观众的偏好。作者不妨考虑一下。可以参考[Sakura_Launcher_GUI](https://github.com/PiDanShouRouZhouXD/Sakura_Launcher_GUI)以及[GalTransl](https://github.com/xd2333/GalTransl)

**Comment by WEIFENG2333** [comment]
ollama后端兼容OpenAi的接口，填入即可。

**Comment by hangajEdu** [comment]
日语还真的是sakaru，其他的模型会卡死
