### ISSUE TITLE
经测试，字幕转换的效果是不错的，希望能增加命令行的调用形式，方便集成到系统中

### ISSUE THREAD

**Issue by prometheus-alien** [WEIFENG2333/VideoCaptioner#8]
### 💡 预期的功能 | Expected Feature

参考工具：CapsWriter-Offline
PS：作者年轻有为，建议润

**Comment by WEIFENG2333** [comment]
CapsWriter-Offline 这个项目已经很成熟了，本项目主要的不同也只是字幕的进一步处理如优化翻译上。字幕转换的完全可以使用 CapsWriter-Offline 项目。

**Comment by prometheus-alien** [comment]
没有啊，CapsWriter-Offline的字幕错别字比较多，断句也没你这个好。就是希望你这个可以增加无界面版的。

**Comment by prometheus-alien** [comment]
> CapsWriter-Offline 这个项目已经很成熟了，本项目主要的不同也只是字幕的进一步处理如优化翻译上。字幕转换的完全可以使用 CapsWriter-Offline 项目。

没有啊，CapsWriter-Offline的字幕错别字比较多，断句也没你这个好。就是希望你这个可以增加无界面版的。

**Comment by WEIFENG2333** [comment]
设计成命令行调用并不是很多人刚需，目前暂时可能不会考虑。等项目逐渐成熟会考虑加上这个功能的。

如果需要调用建议还是在代码基础上修改你的逻辑，这样会更灵活。

**Comment by PikaByter** [comment]
命令行需求+1
