### ISSUE TITLE
重置设置和终止进程

### ISSUE THREAD

**Issue by kingofmagpie** [WEIFENG2333/VideoCaptioner#83]
### 💡 预期的功能 | Expected Feature

大模型设置了ollama之后删除了设置但是无法恢复原有的自带模型了，希望可以增加重置设置的功能，还有就是软件被我乱搞闪退了但是后台的本地whisper还在运行，调用本地大模型翻译时候也是关不掉后台的进程，希望可以添加终止进程的功能

**Comment by WEIFENG2333** [comment]
> 大模型设置了ollama之后删除了设置但是无法恢复原有的自带模型了

删除 base_url 即可
