### ISSUE TITLE
希望可以增加 claude api 的翻譯接口

### ISSUE THREAD

**Issue by coolfish52** [WEIFENG2333/VideoCaptioner#85]
### 💡 预期的功能 | Expected Feature

希望可以新增 ai 平台 claude api 的接口。感謝。

**Comment by WEIFENG2333** [comment]
可以自行使用[oneapi](https://github.com/songquanpeng/one-api)、[newapi](https://github.com/Calcium-Ion/new-api)等项目转换兼容OpenAi的格式。

开发精力实在有限，不打算支持其他格式。
