### ISSUE TITLE
在运行视频字幕合成过程中会出现程序意外关闭的情况

### ISSUE THREAD

**Issue by tiefengsun** [WEIFENG2333/VideoCaptioner#88]
### 问题描述 | Problem Description

在运行视频字幕合成过程中会出现程序意外关闭的情况，发现ffmpeg在后台还在运行，但是UI界面会直接关闭。

**Comment by WEIFENG2333** [comment]
下版本将修复子进程在程序关闭后成为孤儿进程的问题。
