### ISSUE TITLE
希望添加本地lmstudio的api接口

### ISSUE THREAD

**Issue by jacksinofn** [WEIFENG2333/VideoCaptioner#89]
### 💡 预期的功能 | Expected Feature

希望添加本地lmstudio的api接口

**Comment by WEIFENG2333** [comment]
Lmstudio后端兼容OpenAI的接口，请按照文档填入。
```
base_url="http://localhost:1234/v1", 
api_key="lm-studio"
```

[OpenAI Compatibility API](https://lmstudio.ai/docs/api/openai-api)
