### ISSUE TITLE
字幕翻译时是否可以自定义是否进行优化

### ISSUE THREAD

**Issue by MeropZero** [WEIFENG2333/VideoCaptioner#90]
### 💡 预期的功能 | Expected Feature

根据生成的优化日志对比，感觉我使用的素材进行字幕翻译时，未优化的翻译效果更好，不管是从准确性还是流畅度上。
当然不同的内容效果不一样，可能有一些是优化后效果更好。
所以请问能否自定义选择是否进行优化后再翻译，或者在导出字幕文件的时候可以由用户选择使用优化翻译的还是直接翻译的版本。

**Comment by WEIFENG2333** [comment]
这个大概率和模型有关，三步反思发大多数还是有效的。
