### ISSUE TITLE
建议增加一个可以关闭字幕优化的选项，有些字幕优化后把多行合并成了超长的一行

### ISSUE THREAD

**Issue by ganen1933** [WEIFENG2333/VideoCaptioner#91]
### 💡 预期的功能 | Expected Feature

您好大佬！最近翻译SRT字幕文件发现翻译后的字幕会把多行字幕合并成了超长的一行，然后这超长的一行字幕会重复多次，比如翻译后把5行合并成了一行字幕，这合并后的字幕会重复出现5次，不知道这是不是优化字幕导致的，还是因为没有发送时间轴进行翻译导致的，建议增加一个关闭优化字幕的选项，或者有必要的话加一个是否发送时间轴翻译的选项，如果对翻译质量有提升的话，用户会自己考虑是否增加一点成本来获得更高的翻译质量。

**Comment by WEIFENG2333** [comment]
不是特别清楚你的意思，可以大概给个例子吗?

另外与时间轴肯定是没有关系的，软件自动根据原来的时间轴和llm返回的文字比对匹配。
发送时间轴大模型搞不好时间轴都给你整乱了。

**Comment by qqwqtzd** [comment]
支持一下，看了下生成的原始字幕是正常的，但是经过断句优化后字幕意思完全变了，建议增加关闭断句优化的功能

**Comment by ganen1933** [comment]
就是字幕优化后有错乱的情况，有丢失字幕和字幕不合理的合并情况，建议可以增加一个优化字幕的选项开关，不需要优化就可关闭它，很多时候只需要对校对好的字幕通过大模型结合上下文进行总结，反思，和多步翻译。因为如果本身有校对好正确的字幕了，如果翻译前再来一次优化可能效果就更差了，把正确的优化错了。
