### ISSUE TITLE
为什么翻译字幕会生成这么多文件

### ISSUE THREAD

**Issue by cotagxrdhy** [WEIFENG2333/VideoCaptioner#92]
### 🤔 问题描述 Problem Description

![20241129_124519_692_copy](https://github.com/user-attachments/assets/fb85cc72-2aa3-4fa5-b3f2-e75c61fdbc16)
![20241129_124512_439_copy](https://github.com/user-attachments/assets/ef1c3ddb-5778-458e-934e-146c57d2fd2b)

首先是音频文件，本身上传的就是音频文件怎么还要复制到配置文件夹中

其次是字幕文件，我只是需要优化翻译后的字幕文件（与源文件目录一致），其他的没必要生成

感觉文件有点多余了，能不能给一个选项不需要的就不要生成了，谢谢大佬！

**Comment by WEIFENG2333** [comment]
但是有些人还是需要的，比如说带样式的字幕，没翻译前的字幕。

其次也是缓存需要，如果重复处理时检测到有相同文件就不用继续处理了。

反正已经归到一个文件夹里面了，你需要你就用不需要删除即可其实这个不影响的。
