### ISSUE TITLE
本地Whisper转录问题

### ISSUE THREAD

**Issue by DogeCA** [WEIFENG2333/VideoCaptioner#94]
### 🤔 问题描述 Problem Description

搜issue没搜到太多信息，就另起一个了，见谅
原视频约1小时40分，识别语言为粤语，使用Whisper是因为它可以直接将粤语口语转换为书面的普通话形式，B、J接口的结果都不太好
音频为5.1中提取的人声音轨，理论上其它声音影响识别的概率很低
如果我漏了什么信息没有提供还请提醒我进行补充

使用small模型时：
大片丢字幕（这里是最后测的，没截图）

使用Medium模型时：
转录时会卡在94%正在转换，此时电脑没有占用，等待10分钟依旧
<img width="1097" alt="屏幕截图 2024-11-30 004757" src="https://github.com/user-attachments/assets/74cf8b58-226e-40d3-9c57-83d21eb16a83">

使用Large-V1模型时：
可转录出字幕，但内容会“抽风”，重复了一大片，如下图
使用的视频不管是原视频，还是截成30分钟的片段，依然出现此情况
以前使用Whisper也遇到过类似情况，不知是否有解决方案
<img width="377" alt="屏幕截图 2024-11-30 005149" src="https://github.com/user-attachments/assets/eb9666a3-c19c-405f-b611-d00b932f4501">
<img width="502" alt="屏幕截图 2024-11-30 005230" src="https://github.com/user-attachments/assets/e5b45fbf-6001-4dc6-b002-358c3a0809bd">
<img width="788" alt="屏幕截图 2024-11-30 005312" src="https://github.com/user-attachments/assets/26c782d0-6774-4a21-be0d-f7df9d0993bb">

使用Large-V2模型时：
大片丢字幕
<img width="629" alt="屏幕截图 2024-11-30 010613" src="https://github.com/user-attachments/assets/44380992-9d65-4446-ae38-b81f129d531c">

软件本体在优化后转至合成压制时偶尔会闪退，但后台FFmpeg仍在进行压制任务

补充1：刚刚用了一下Whisper-Desktop配合Medium能顺利转录，字幕抽风问题也减少至几十个，不过时轴有些不对

等再测到什么再补充一下，希望作者大大能看看以上问题是什么情况

**Comment by WEIFENG2333** [comment]
感谢反馈， 新版本会有faster-whisper，支持vad，这些现象大概率可以解决。

ffmpeg是退出管理没做好，后续会优化的。

**Comment by feiyudashen** [comment]
使用fast-whisper,调整了vad参数，还是有漏识别的问题，如何彻底解决呢？
