### ISSUE TITLE
可能是分辨率切换会导致崩溃的问题。

### ISSUE THREAD

**Issue by darkangellxc-hardname** [WEIFENG2333/VideoCaptioner#97]
### 问题描述 | Problem Description

1、我有两个显示器，都是1080P的，但经常性的，我将窗口从A显示器拖到B显示器（或反过来）就会卡死闪退，可能也不是分辨率变了导致的，也许是显卡驱动的问题？我闹不准。
2、似乎火绒会对主程序报毒，不定期报毒。
log我就不放了，似乎log只记录了转录和优化的任务过程中的控制台信息，我报告的这两个情况在log中都没有体现。

**Comment by WEIFENG2333** [comment]
暂时我无法复现，但是也许下个版本可以修复这个问题。
