### ISSUE TITLE
希望加强批处理能力

### ISSUE THREAD

**Issue by darkangellxc-hardname** [WEIFENG2333/VideoCaptioner#98]
### 💡 预期的功能 | Expected Feature

我有一些课程录音
我发现用您的这个软件可以方便的转为优质的字幕
再配合豆包等模型可生成效果不错的markmap思维导图
这对于我的学习非常有帮助
但我需要一条一条手动语音转录为srt，再一条一条手动优化内容（同时还要手动添加文稿提示词，同一学科的提示词往往是雷同的）
我虽有一点点python知识，但您的代码对我来说过于复杂（我甚至无法将它正常打包），自己写批处理分支对我而言太难了。
恳请您考虑加强软件的批处理能力

另：
您在readme中说明，软件内置基础大语言模型（gpt-4o-mini），但我翻了下源码，未找到gpt-4o-mini的模型，也未在安装后的软件目录找到相应模型，设置中也没有下载的地方，我只能通过自有API方式对接LLM。也许我的方法不对？

**Comment by WEIFENG2333** [comment]
软件有批量转换音视频的功能。

另外，大模型就是通过api调用的，你不填写就是默认使用公益的4o-mini模型，不需要下载

**Comment by 123hi123** [comment]
我感覺還可以加入鏈結轉錄的功能在批處裡當中 
順便用ai總結每部影片的重點

**Comment by WEIFENG2333** [comment]
目前精力有限，批量字幕功能后期会考虑。
